import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'
import './globals.css'
import type React from 'react'

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: React.PropsWithChildren<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-google-analytics-opt-out="">
      <body className={`${robotoSans.variable} ${robotoMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
