/**
 * @module NumericKeypadKeys
 *
 * @file
 *
 *   These keys are found on the keyboard's numeric keypad. However, not all are
 *   present on every keyboard. Although typical numeric keypads have numeric
 *   keys from `0` to `9` (encoded as `"0"` through `"9"`), some multimedia
 *   keyboards include additional number keys for higher numbers.
 *
 * > [!NOTE]
 *
 * > The `10` key, if present, generates events with the `key` value of `"0"`.
 * @generated
 */

/**
 * The decimal point key (typically `.` or `,` depending on the region). In
 * newer browsers, this value to be the character generated by the decimal key
 * (one of those two characters).
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_DECIMAL` (0x6E)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadDecimal` (0x41)
 *
 * Linux virtual key code: `GDK_KEY_KP_Decimal` (0xFFAE)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_DOT` (158)
 *
 * @deprecated
 * @generated
 */
export type Decimal = 'Decimal'

/**
 * The decimal point key (typically `.` or `,` depending on the region). In
 * newer browsers, this value to be the character generated by the decimal key
 * (one of those two characters).
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_DECIMAL` (0x6E)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadDecimal` (0x41)
 *
 * Linux virtual key code: `GDK_KEY_KP_Decimal` (0xFFAE)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_DOT` (158)
 *
 * @deprecated
 * @generated
 */
export const Decimal: Decimal = 'Decimal'

/**
 * The `11` key found on certain media numeric keypads.
 *
 * @generated
 */
export type Key11 = 'Key11'

/**
 * The `11` key found on certain media numeric keypads.
 *
 * @generated
 */
export const Key11: Key11 = 'Key11'

/**
 * The `12` key found on certain media numeric keypads.
 *
 * @generated
 */
export type Key12 = 'Key12'

/**
 * The `12` key found on certain media numeric keypads.
 *
 * @generated
 */
export const Key12: Key12 = 'Key12'

/**
 * The numeric keypad's multiplication key, `*`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_MULTIPLY` (0x6A)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadMultiply` (0x43)
 *
 * Linux virtual key code: `GDK_KEY_KP_Multiply` (0xFFAA) `Qt::Key_Multiply`
 * (0x0D7)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_MULTIPLY` (155)
 *
 * @deprecated
 * @generated
 */
export type Multiply = 'Multiply'

/**
 * The numeric keypad's multiplication key, `*`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_MULTIPLY` (0x6A)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadMultiply` (0x43)
 *
 * Linux virtual key code: `GDK_KEY_KP_Multiply` (0xFFAA) `Qt::Key_Multiply`
 * (0x0D7)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_MULTIPLY` (155)
 *
 * @deprecated
 * @generated
 */
export const Multiply: Multiply = 'Multiply'

/**
 * The numeric keypad's addition key, `+`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_ADD` (0x6B)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadPlus` (0x45)
 *
 * Linux virtual key code: `GDK_KEY_KP_Add` (0xFFAB)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_ADD` (157)
 *
 * @deprecated
 * @generated
 */
export type Add = 'Add'

/**
 * The numeric keypad's addition key, `+`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_ADD` (0x6B)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadPlus` (0x45)
 *
 * Linux virtual key code: `GDK_KEY_KP_Add` (0xFFAB)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_ADD` (157)
 *
 * @deprecated
 * @generated
 */
export const Add: Add = 'Add'

/**
 * The numeric keypad's division key, `/`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_DIVIDE` (0x6F)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadDivide` (0x4B)
 *
 * Linux virtual key code: `GDK_KEY_KP_Divide` (0xFFAF) `Qt::Key_Slash` (0x2F)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_DIVIDE` (154)
 *
 * @deprecated
 * @generated
 */
export type Divide = 'Divide'

/**
 * The numeric keypad's division key, `/`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_DIVIDE` (0x6F)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadDivide` (0x4B)
 *
 * Linux virtual key code: `GDK_KEY_KP_Divide` (0xFFAF) `Qt::Key_Slash` (0x2F)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_DIVIDE` (154)
 *
 * @deprecated
 * @generated
 */
export const Divide: Divide = 'Divide'

/**
 * The numeric keypad's subtraction key, `-`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_SUBTRACT` (0x6D)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadMinus` (0x4E)
 *
 * Linux virtual key code: `GDK_KEY_KP_Subtract` (0xFFAD)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_SUBTRACT` (156)
 *
 * @deprecated
 * @generated
 */
export type Subtract = 'Subtract'

/**
 * The numeric keypad's subtraction key, `-`.
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_SUBTRACT` (0x6D)
 *
 * Mac virtual key code: `kVK_ANSI_KeypadMinus` (0x4E)
 *
 * Linux virtual key code: `GDK_KEY_KP_Subtract` (0xFFAD)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_SUBTRACT` (156)
 *
 * @deprecated
 * @generated
 */
export const Subtract: Subtract = 'Subtract'

/**
 * The numeric keypad's places separator character. (In the United States this
 * is a comma, but elsewhere it is frequently a period.)
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_SEPARATOR` (0x6C)
 *
 * Mac virtual key code: `kVK_JIS_KeypadComma` (0x5F)
 *
 * Linux virtual key code: `GDK_KEY_KP_Separator` (0xFFAC)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_COMMA` (159)
 *
 * @generated
 */
export type Separator = 'Separator'

/**
 * The numeric keypad's places separator character. (In the United States this
 * is a comma, but elsewhere it is frequently a period.)
 *
 * While older browsers used words like `"Add"`, `"Decimal"`, `"Multiply"`, and
 * so forth modern browsers identify these using the actual character ( `"+"`,
 * `"."`, `"*"`, and so forth).
 *
 * Windows virtual key code: `VK_SEPARATOR` (0x6C)
 *
 * Mac virtual key code: `kVK_JIS_KeypadComma` (0x5F)
 *
 * Linux virtual key code: `GDK_KEY_KP_Separator` (0xFFAC)
 *
 * Android virtual key code: `KEYCODE_NUMPAD_COMMA` (159)
 *
 * @generated
 */
export const Separator: Separator = 'Separator'
