/** biome-ignore-all lint/plugin/drizzle: it's not drizzle */

import * as Data from 'effect/Data'
import * as Effect from 'effect/Effect'
import type * as HttpClient from 'effect/unstable/http/HttpClient'
import * as HttpClientError from 'effect/unstable/http/HttpClientError'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

export interface RegistryMetadataOther {
  readonly data_size: number
}

export interface RegistryMetadataSizes {
  readonly external: number
  readonly file: number
  readonly active: number
}

/**
 * Registry Metadata
 */
export interface RegistryMetadata {
  readonly data_size: number
  readonly doc_count: number
  readonly other: RegistryMetadataOther
  readonly update_seq: number
  readonly disk_size: number
  readonly disk_format_version: number
  readonly doc_del_count: number
  readonly uuid: string
  readonly instance_start_time: string
  readonly committed_update_seq: number
  readonly compacted_seq: number
  readonly db_name: string
  readonly purge_seq: number
  readonly sizes: RegistryMetadataSizes
  readonly engine: string
}

export type All200 = ReadonlyArray<Record<string, unknown>>

/**
 * Generic NpmError
 */
export interface NpmError {
  /**
   * Error message
   */
  readonly error?: string | undefined
  readonly code?: string | undefined
  /**
   * Error message
   */
  readonly message?: string | undefined
  /**
   * HTTP Status Code
   */
  readonly statusCode?: number | undefined
}

/**
 * A mapping of dist tags to the versions they point to.
 */
export interface DistTags {
  /**
   * Latest version number
   */
  readonly latest: string
}

/**
 * An object mapping versions to the time published, along with created and modified timestamps.
 */
export interface VersionsToTimestamps {
  /**
   * ISO string of when the package was created.
   */
  readonly created: string
  /**
   * ISO string of the last time this package was modified.
   */
  readonly modified: string
}

/**
 * Represents a person associated to a package. It has at least one of the following fields defined:
 * - name: a freeform string name
 * - email: an email address
 * - url: a url for a web page with more information about the author
 * Historically no validation has been performed on those fields; they are generated by parsing user-provided data in package.json at publication time.
 */
export interface Person {
  /**
   * A freeform string name
   */
  readonly name?: string | undefined
  /**
   * An email address
   */
  readonly email?: string | undefined
  /**
   * A url for a web page with more information about the author
   */
  readonly url?: string | undefined
}

/**
 * It represents the bug tracking methods.
 */
export interface BugTracker {
  /**
   * The url of the project's issue tracker.
   */
  readonly url?: string | undefined
  /**
   * The email address to which issues should be reported.
   */
  readonly email?: string | undefined
}

/**
 * An object specifying the repository where the source for this package might be found.
 */
export interface Repository {
  /**
   * Repository type (for example, `git`)
   */
  readonly type?: string | undefined
  /**
   * Url of the repository
   */
  readonly url: string
  /**
   * Specific directory in the repository containing the package (for example, a directory in a monorepo)
   */
  readonly directory?: string | undefined
}

/**
 * Package metadata describes a package for its consumers: who wrote it, where its repository is, and what versions of it have been published. It also contains a description of each version of a package present in the registry, listing its dependencies, giving the url of its tarball, and so on. Package metadata is useful for finding packages and for installing them.
 */
export interface PackageMetadata {
  /**
   * The revision number of this version of the document in CouchDB.
   */
  readonly _rev: string
  /**
   * ISO string of the last time this package was modified.
   */
  readonly modified: string
  /**
   * Final and detailed search score values
   */
  readonly 'dist-tags': DistTags
  /**
   * A mapping of version numbers to objects containing the information needed to install that version.
   */
  readonly versions: Record<string, unknown>
  /**
   * Mapping of version numbers to publishing timestamps
   */
  readonly time: VersionsToTimestamps
  /**
   * An object whose keys are the npm user names of people who have starred the package.
   */
  readonly users?: Record<string, unknown> | undefined
  /**
   * The package name, used as an ID in CouchDB
   */
  readonly _id: string
  /**
   * The package name
   */
  readonly name: string
  readonly author?: Person | undefined
  /**
   * Bug tracker
   */
  readonly bugs?: BugTracker | undefined
  /**
   * List of package contributors
   */
  readonly contributors?: ReadonlyArray<Person> | undefined
  /**
   * A short description of the package
   */
  readonly description?: string | undefined
  /**
   * The url of the project homepage.
   */
  readonly homepage?: string | undefined
  /**
   * Array of string keywords
   */
  readonly keywords?: ReadonlyArray<string> | undefined
  /**
   * The SPDX identifier of the package's license
   */
  readonly license?: string | undefined
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  readonly maintainers?: ReadonlyArray<Person> | undefined
  /**
   * The first 64K of the README data for the most-recently published version of the package
   */
  readonly readme?: string | undefined
  /**
   * The name of the file from which the readme data was taken.
   */
  readonly readmeFilename?: string | undefined
  /**
   * Repository containing the package's source
   */
  readonly repository?: Repository | undefined
}

/**
 * The dist object is generated by npm and may be relied upon. Each dist object has at least two fields:
 * - tarball: the url of the tarball containing the payload for this package
 * - shasum: the SHA-1 sum of the tarball
 * - integrity: since Apr 2017, string in the format `<hashAlgorithm>-<base64-hash>`, refer the Subresource Integrity and cacache package for more
 * - fileCount: since Feb 2018, the number of files in the tarball, folder excluded
 * - unpackedSize: since Feb 2018, the total byte of the unpacked files in the tarball
 * - npm-signature: since Apr 2018, a PGP signature of `<package>@<version>:<integrity>`, refer the npm blog and doc for more (in the future) a SHA-2 512 sum of the tarball
 */
export interface DistInfo {
  /**
   * The url of the tarball containing the payload for this package
   */
  readonly tarball: string
  /**
   * The SHA-1 sum of the tarball
   */
  readonly shasum: string
  /**
   * Since Apr 2017, string in the format `<hashAlgorithm>-<base64-hash>`, refer the Subresource Integrity and cacache package for more
   */
  readonly integrity?: string | undefined
  /**
   * Since Feb 2018, the number of files in the tarball, folder excluded
   */
  readonly fileCount?: number | undefined
  /**
   * Since Feb 2018, the total byte of the unpacked files in the tarball
   */
  readonly unpackedSize?: number | undefined
  /**
   * PGP signature of `<package>@<version>:<integrity>`
   */
  readonly 'npm-signature'?: string | undefined
  readonly signatures?:
    | ReadonlyArray<{
        readonly keyid: string
        readonly sig: string
      }>
    | undefined
}

/**
 * An object specifying the funding info for this package.
 */
export interface Funding {
  /**
   * Funding type
   */
  readonly type?: string | undefined
  /**
   * Url of the funding
   */
  readonly url: string
}

/**
 * Internal npm data
 */
export interface NpmOperationalInternal {
  readonly host: string
  readonly tmp: string
}

/**
 * Objects containing the information needed to install that version
 */
export interface PackageVersionMetadata {
  /**
   * The version string for this version
   */
  readonly version: string
  /**
   * The deprecation warnings message of this version
   */
  readonly deprecated?: string | undefined
  /**
   * A mapping of other packages this version depends on to the required semver ranges
   */
  readonly dependencies?: Record<string, unknown> | undefined
  /**
   * An object mapping package names to the required semver ranges of optional dependencies
   */
  readonly optionalDependencies?: Record<string, unknown> | undefined
  /**
   * A mapping of package names to the required semver ranges of development dependencies
   */
  readonly devDependencies?: Record<string, unknown> | undefined
  /**
   * An array of dependencies bundled with this version
   */
  readonly bundleDependencies?: ReadonlyArray<string> | undefined
  /**
   * A mapping of package names to the required semver ranges of development dependencies
   */
  readonly peerDependencies?: Record<string, unknown> | undefined
  /**
   * A mapping of dependency package names to be replaced with another version, or another package entirely
   */
  readonly overrides?: Record<string, unknown> | undefined
  /**
   * A mapping of bin commands to set up for this version
   */
  readonly bin?: Record<string, unknown> | undefined
  /**
   * An array of directories included by this version
   */
  readonly directories?: ReadonlyArray<string> | undefined
  readonly dist: DistInfo
  readonly engines?:
    | {
        /**
         * The node engines required for this version to run, if specified
         */
        readonly node?: string | undefined
        /**
         * The npm engines required for this version to run, if specified
         */
        readonly npm?: string | undefined
      }
    | undefined
  /**
   * `true` if this version is known to have a shrinkwrap that must be used to install it; false if this version is known not to have a shrinkwrap. If this field is `undefined`, the client must determine through other means if a shrinkwrap exists.
   */
  readonly _hasShrinkwrap?: boolean | undefined
  /**
   * The version of node used to publish the package
   */
  readonly _nodeVersion?: string | undefined
  /**
   * User who published this package version
   */
  readonly _npmUser: Person
  /**
   * The version of the npm client used to publish the package
   */
  readonly _npmVersion?: string | undefined
  /**
   * Commit hash corresponding to the published version
   */
  readonly gitHead?: string | undefined
  /**
   * The package's entry point (e.g., index.js or main.js)
   */
  readonly main?: string | undefined
  /**
   * The package's entry point (e.g., index.js or main.js) if the module is meant to be used client-side
   */
  readonly browser?: string | undefined
  /**
   * The "scripts" property is a dictionary containing script commands that are run at various times in the lifecycle of your package. The key is the lifecycle event, and the value is the command to run at that point.
   */
  readonly scripts?: Record<string, unknown> | undefined
  /**
   * A "config" object can be used to set configuration parameters used in package scripts that persist across upgrades.
   */
  readonly config?: Record<string, unknown> | undefined
  /**
   * A set of config values that will be used at publish-time
   */
  readonly publishConfig?: Record<string, unknown> | undefined
  readonly funding?: Funding | undefined
  /**
   * An array of file patterns that describes the entries to be included when the package is installed as a dependency.
   */
  readonly files?: ReadonlyArray<string> | undefined
  /**
   * An array of operating systems the package will run on
   */
  readonly os?: ReadonlyArray<string> | undefined
  /**
   * If the package code only runs on certain cpu architectures
   */
  readonly cpu?: ReadonlyArray<string> | undefined
  /**
   * If the package is private or not
   */
  readonly private?: boolean | undefined
  /**
   * An array of file patterns that describes locations within the local file system that the install client should look up to find each workspace that needs to be symlinked to the top level node_modules folder.
   */
  readonly workspaces?: ReadonlyArray<string> | undefined
  /**
   * Internal npm data
   */
  readonly _npmOperationalInternal?: NpmOperationalInternal | undefined
  /**
   * The package name, used as an ID in CouchDB
   */
  readonly _id: string
  /**
   * The package name
   */
  readonly name: string
  readonly author?: Person | undefined
  /**
   * Bug tracker
   */
  readonly bugs?: BugTracker | undefined
  /**
   * List of package contributors
   */
  readonly contributors?: ReadonlyArray<Person> | undefined
  /**
   * A short description of the package
   */
  readonly description?: string | undefined
  /**
   * The url of the project homepage.
   */
  readonly homepage?: string | undefined
  /**
   * Array of string keywords
   */
  readonly keywords?: ReadonlyArray<string> | undefined
  /**
   * The SPDX identifier of the package's license
   */
  readonly license?: string | undefined
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  readonly maintainers?: ReadonlyArray<Person> | undefined
  /**
   * The first 64K of the README data for the most-recently published version of the package
   */
  readonly readme?: string | undefined
  /**
   * The name of the file from which the readme data was taken.
   */
  readonly readmeFilename?: string | undefined
  /**
   * Repository containing the package's source
   */
  readonly repository?: Repository | undefined
}

export interface V1SearchParams {
  readonly text?: string | null | undefined
  readonly size?: number | null | undefined
  readonly from?: number | null | undefined
  readonly quality?: number | null | undefined
  readonly popularity?: number | null | undefined
  readonly maintenance?: number | null | undefined
}

/**
 * It contains a collection of links of pages associated to the package.
 */
export interface PackageLinks {
  /**
   * The NPM url of the package
   */
  readonly npm?: string | undefined
  /**
   * The url of the project homepage.
   */
  readonly homepage?: string | undefined
  /**
   * The url of the project repository.
   */
  readonly repository?: string | undefined
  /**
   * The url of the project's issue tracker and / or the email address to which issues should be reported.
   */
  readonly bugs?: string | undefined
}

/**
 * It contains abbreviated package metadata returned by searching the registry for packages.
 */
export interface PackageSearchResult {
  /**
   * The package name
   */
  readonly name: string
  /**
   * Latest package version number
   */
  readonly version: string
  /**
   * The scope of the package
   */
  readonly scope?: string | undefined
  /**
   * A short description of the package
   */
  readonly description?: string | undefined
  /**
   * Array of string keywords
   */
  readonly keywords?: ReadonlyArray<string> | undefined
  /**
   * Publishing timestamp for the latest version
   */
  readonly date: string
  /**
   * Links for pages associated to the package
   */
  readonly links: PackageLinks
  /**
   * The package publisher
   */
  readonly publisher: Person
  /**
   * The package author
   */
  readonly author?: Person | undefined
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  readonly maintainers?: ReadonlyArray<Person> | undefined
}

/**
 * It contains the search score values for the quality, popularity and maintenance categories.
 */
export interface SearchScoreDetail {
  /**
   * Package quality score value
   */
  readonly quality: number
  /**
   * Package popularity score value
   */
  readonly popularity: number
  /**
   * Package maintenance score value
   */
  readonly maintenance: number
}

/**
 * It contains the final and detailed search score values.
 */
export interface SearchScore {
  /**
   * Final search score value, computed from the detailed scores
   */
  readonly final: number
  /**
   * Detailed search score values
   */
  readonly detail: SearchScoreDetail
}

/**
 * It contains flag attributes categorizing the package.
 */
export interface PackageFlags {
  /**
   * If true, package version is `<1.0.0`
   */
  readonly unstable?: boolean | undefined
  /**
   * If true, package is insecure or has vulnerable dependencies
   */
  readonly insecure?: boolean | undefined
}

/**
 * It contains the search result for a single package and its search score.
 */
export interface SearchResult {
  /**
   * Abbreviated package metadata
   */
  readonly package: PackageSearchResult
  /**
   * Final and detailed search score values
   */
  readonly score?: SearchScore | undefined
  /**
   * Search score value; may be different from `score.final`
   */
  readonly searchScore: number
  /**
   * Flag attributes for the package
   */
  readonly flags?: PackageFlags | undefined
}

/**
 * It contains the results returned by the registry for a query.
 */
export interface SearchResults {
  readonly objects: ReadonlyArray<SearchResult>
  /**
   * Total number of search results corresponding to a query; may be higher than the number of `objects`
   */
  readonly total: number
  /**
   * Date at which the search happened
   */
  readonly time: string
}

/**
 * Lists the number of downloads for the registry in a given time period.
 */
export interface RegistryDownloads {
  /**
   * Total number of downloads
   */
  readonly downloads: number
  /**
   * Date of the first day (inclusive)
   */
  readonly start: string
  /**
   * Date of the last day (inclusive)
   */
  readonly end: string
}

/**
 * Lists the number of downloads for a package in a given time period.
 */
export interface PackageDownloads {
  /**
   * Package name
   */
  readonly package: string
  /**
   * Total number of downloads
   */
  readonly downloads: number
  /**
   * Date of the first day (inclusive)
   */
  readonly start: string
  /**
   * Date of the last day (inclusive)
   */
  readonly end: string
}

/**
 * Lists the number of downloads in a given day.
 */
export interface DownloadsPerDay {
  readonly downloads: number
  readonly day: string
}

/**
 * Lists the number of downloads for a package for each day in a given time period.
 */
export interface DailyRegistryDownloads {
  /**
   * Download counts per day
   */
  readonly downloads: ReadonlyArray<DownloadsPerDay>
  /**
   * Date of the first day (inclusive)
   */
  readonly start: string
  /**
   * Date of the last day (inclusive)
   */
  readonly end: string
}

/**
 * Lists the number of downloads for a package for each day in a given time period.
 */
export interface DailyPackageDownloads {
  /**
   * Package name
   */
  readonly package: string
  /**
   * Download counts per day
   */
  readonly downloads: ReadonlyArray<DownloadsPerDay>
  /**
   * Date of the first day (inclusive)
   */
  readonly start: string
  /**
   * Date of the last day (inclusive)
   */
  readonly end: string
}

/**
 * Package download count for specific versions.
 */
export interface PackageVersionsDownloadCount {
  /**
   * Package name
   */
  readonly package: string
  /**
   * A map containing the package version as key and the download count as value.
   */
  readonly downloads: Record<string, unknown>
}

export interface UserOrgCouchdbUserUserParams {
  readonly 'npm-otp'?: string | undefined
}

export interface LoginRequest {
  /**
   * NPM username.
   */
  readonly name: string
  /**
   * NPM user password.
   */
  readonly password: string
  readonly readonly?: boolean | undefined
  readonly cidr_whitelist?: ReadonlyArray<string> | undefined
}

export interface LoginResponse {
  /**
   * Bearer token
   */
  readonly token?: string | undefined
  /**
   * If login succeded
   */
  readonly ok?: boolean | undefined
}

export interface LegacyStatus {
  /**
   * If operation succeded.
   */
  readonly ok: boolean
}

export interface Profile {
  /**
   * User name
   */
  readonly name: string
  /**
   * User email
   */
  readonly email: string
  /**
   * Email verification status
   */
  readonly email_verified: boolean
  /**
   * When the account was created
   */
  readonly created: string
  /**
   * When the account was updated
   */
  readonly updated?: string | undefined
  /**
   * CIDR whitelist
   */
  readonly cidr_whitelist?: ReadonlyArray<string> | undefined
  /**
   * User full name
   */
  readonly fullname?: string | undefined
  /**
   * User homepage url
   */
  readonly homepage?: string | undefined
  readonly freenode?: string | undefined
  /**
   * Twitter username
   */
  readonly twitter?: string | undefined
  /**
   * GitHub username
   */
  readonly github?: string | undefined
}

export interface NpmV1UserParams {
  readonly 'npm-otp'?: string | undefined
}

export interface PasswordUpdateRequest {
  readonly old: string
  readonly 'new': string
}

export interface ProfileUpdateRequest {
  /**
   * Password change request data
   */
  readonly password?: PasswordUpdateRequest | undefined
  /**
   * User email
   */
  readonly email?: string | undefined
  /**
   * User full name
   */
  readonly fullname?: string | undefined
  /**
   * User homepage url
   */
  readonly homepage?: string | undefined
  readonly freenode?: string | undefined
  /**
   * Twitter username
   */
  readonly twitter?: string | undefined
  /**
   * GitHub username
   */
  readonly github?: string | undefined
}

/**
 * Urls to navigate results
 */
export interface PageUrls {
  /**
   * Url of the next results
   */
  readonly next?: string | undefined
  /**
   * Url of the previous results
   */
  readonly prev?: string | undefined
}

/**
 * Objects containing the list of user's tokens
 */
export interface TokenPage {
  readonly userHasOldFormatToken: boolean
  /**
   * Number of total items
   */
  readonly total?: number | undefined
  readonly objects: ReadonlyArray<Record<string, unknown>>
  /**
   * Urls to navigate results
   */
  readonly urls: PageUrls
}

export interface NpmV1TokensParams {
  readonly 'npm-otp'?: string | undefined
}

export interface TokenCreationRequest {
  /**
   * NPM User password
   */
  readonly password: string
  readonly readonly?: boolean | undefined
  readonly cidr_whitelist?: ReadonlyArray<string> | undefined
}

export interface Token {
  /**
   * \[REDACTED\] on subsequent display. The "Bearer" token.
   */
  readonly token: string
  /**
   * sha512 hash of the token UUID
   */
  readonly key: string
  readonly automation: boolean
  readonly cidr_whitelist?: ReadonlyArray<string> | undefined
  readonly created: string
  readonly updated: string
  readonly readonly: boolean
}

export interface NpmV1TokensTokenUuidParams {
  readonly 'npm-otp'?: string | undefined
}

export interface UserTokenTokenParams {
  readonly 'npm-otp'?: string | undefined
}

export interface NpmV1HooksParams {
  readonly package?: string | undefined
  readonly limit?: number | undefined
  readonly offset?: number | undefined
}

/**
 * Type of object being watched; `package`, `scope`, or `owner`.
 */
export type HookType = 'package' | 'scope' | 'owner'

/**
 * Hook object
 */
export interface Hook {
  /**
   * Hook id
   */
  readonly id: string
  /**
   * NPM user name.
   */
  readonly username: string
  /**
   * Name of package or organization/user scope to watch, e.g, `@scope` or `package`.
   */
  readonly name: string
  /**
   * Full uri of the endpoint to post the notification to.
   */
  readonly endpoint: string
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  readonly secret: string
  readonly type: HookType
  /**
   * Hook creation date
   */
  readonly created: string
  /**
   * Hook update date
   */
  readonly updated: string
  readonly delivered: boolean
  /**
   * Hook last delivery date
   */
  readonly last_delivery?: string | undefined
  /**
   * Response code
   */
  readonly response_code: number
  /**
   * Hook status
   */
  readonly status: string
  /**
   * If the Hook has been deleted
   */
  readonly deleted?: boolean | undefined
}

/**
 * It contains the results returned by the hook search.
 */
export interface HookSearchResults {
  readonly objects: ReadonlyArray<Hook>
  /**
   * Total number of search results corresponding to a query; may be higher than the number of `objects`
   */
  readonly total: number
}

export interface NpmV1HooksHookParams {
  readonly 'npm-otp'?: string | undefined
}

/**
 * Hook creation request object
 */
export interface HookCreateRequest {
  readonly type: HookType
  /**
   * Name of package or organization/user scope to watch, e.g, `@scope` or `package`.
   */
  readonly name: string
  /**
   * Full uri of the endpoint to post the notification to.
   */
  readonly endpoint: string
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  readonly secret: string
}

export interface NpmV1HooksHookIdParams {
  readonly 'npm-otp'?: string | undefined
}

/**
 * Hook update request object
 */
export interface HookUpdateRequest {
  /**
   * Full uri of the endpoint to post the notification to.
   */
  readonly endpoint: string
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  readonly secret: string
}

export const make = (
  httpClient: HttpClient.HttpClient,
  options: {
    readonly transformClient?:
      | ((
          client: HttpClient.HttpClient,
        ) => Effect.Effect<HttpClient.HttpClient>)
      | undefined
  } = {},
): Client => {
  const unexpectedStatus = (response: HttpClientResponse.HttpClientResponse) =>
    Effect.flatMap(
      Effect.orElseSucceed(response.json, () => 'Unexpected status code'),
      description =>
        Effect.fail(
          new HttpClientError.HttpClientError({
            reason: new HttpClientError.StatusCodeError({
              request: response.request,
              response,
              description:
                typeof description === 'string'
                  ? description
                  : JSON.stringify(description),
            }),
          }),
        ),
    )
  const transformClient = options.transformClient
  const withResponse: <A, E>(
    f: (response: HttpClientResponse.HttpClientResponse) => Effect.Effect<A, E>,
  ) => (
    request: HttpClientRequest.HttpClientRequest,
  ) => Effect.Effect<any, any> = transformClient
    ? f => request =>
        Effect.flatMap(
          Effect.flatMap(transformClient(httpClient), client =>
            client.execute(request),
          ),
          f,
        )
    : f => request => Effect.flatMap(httpClient.execute(request), f)
  const decodeSuccess = <A>(response: HttpClientResponse.HttpClientResponse) =>
    response.json as Effect.Effect<A, HttpClientError.HttpClientError>
  const decodeVoid = (_response: HttpClientResponse.HttpClientResponse) =>
    Effect.void
  const decodeError =
    <Tag extends string, E>(tag: Tag) =>
    (
      response: HttpClientResponse.HttpClientResponse,
    ): Effect.Effect<
      never,
      ClientError<Tag, E> | HttpClientError.HttpClientError
    > =>
      Effect.flatMap(
        response.json as Effect.Effect<E, HttpClientError.HttpClientError>,
        cause => Effect.fail(ClientError(tag, cause, response)),
      )
  const onRequest = (
    successCodes: ReadonlyArray<string>,
    errorCodes?: Record<string, string>,
  ) => {
    const cases: any = { orElse: unexpectedStatus }
    for (const code of successCodes) {
      cases[code] = decodeSuccess
    }
    if (errorCodes) {
      for (const [code, tag] of Object.entries(errorCodes)) {
        cases[code] = decodeError(tag)
      }
    }
    if (successCodes.length === 0) {
      cases['2xx'] = decodeVoid
    }
    return withResponse(HttpClientResponse.matchStatus(cases) as any)
  }
  return {
    httpClient,
    'GET/': () => HttpClientRequest.get(`/`).pipe(onRequest(['2xx'])),
    'GET/-/all': () =>
      HttpClientRequest.get(`/-/all`).pipe(
        onRequest(['2xx'], { '404': 'NpmError' }),
      ),
    'GET/{packageName}': packageName =>
      HttpClientRequest.get(`/${packageName}`).pipe(
        onRequest(['2xx'], { '404': 'NpmError' }),
      ),
    'GET/{packageName}/{version}': (packageName, version) =>
      HttpClientRequest.get(`/${packageName}/${version}`).pipe(
        onRequest(['2xx'], { '404': 'NpmError' }),
      ),
    'GET/-/v1/search': options =>
      HttpClientRequest.get(`/-/v1/search`).pipe(
        HttpClientRequest.setUrlParams({
          text: options?.text as any,
          size: options?.size as any,
          from: options?.from as any,
          quality: options?.quality as any,
          popularity: options?.popularity as any,
          maintenance: options?.maintenance as any,
        }),
        onRequest(['2xx']),
      ),
    'GET/downloads/point/{period}': period =>
      HttpClientRequest.get(`/downloads/point/${period}`).pipe(
        onRequest(['2xx']),
      ),
    'GET/downloads/point/{period}/{packageName}': (period, packageName) =>
      HttpClientRequest.get(`/downloads/point/${period}/${packageName}`).pipe(
        onRequest(['2xx']),
      ),
    'GET/downloads/range/{period}': period =>
      HttpClientRequest.get(`/downloads/range/${period}`).pipe(
        onRequest(['2xx']),
      ),
    'GET/downloads/range/{period}/{packageName}': (period, packageName) =>
      HttpClientRequest.get(`/downloads/range/${period}/${packageName}`).pipe(
        onRequest(['2xx']),
      ),
    'GET/versions/{packageName}/last-week': packageName =>
      HttpClientRequest.get(`/versions/${packageName}/last-week`).pipe(
        onRequest(['2xx']),
      ),
    'PUT/-/user/org.couchdb.user:{user}': (user, options) =>
      HttpClientRequest.put(`/-/user/org.couchdb.user:${user}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        onRequest(['2xx'], { '401': 'LegacyStatus' }),
      ),
    'GET/-/npm/v1/user': () =>
      HttpClientRequest.get(`/-/npm/v1/user`).pipe(onRequest(['2xx'])),
    'POST/-/npm/v1/user': options =>
      HttpClientRequest.post(`/-/npm/v1/user`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        onRequest(['2xx']),
      ),
    'GET/-/npm/v1/tokens': () =>
      HttpClientRequest.get(`/-/npm/v1/tokens`).pipe(onRequest(['2xx'])),
    'POST/-/npm/v1/tokens': options =>
      HttpClientRequest.post(`/-/npm/v1/tokens`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        onRequest(['2xx']),
      ),
    'DELETE/-/npm/v1/tokens/token/{uuid}': (uuid, options) =>
      HttpClientRequest.delete(`/-/npm/v1/tokens/token/${uuid}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        onRequest([]),
      ),
    'DELETE/-/user/token/{token}': (token, options) =>
      HttpClientRequest.delete(`/-/user/token/${token}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        onRequest(['2xx']),
      ),
    'GET/-/npm/v1/hooks': options =>
      HttpClientRequest.get(`/-/npm/v1/hooks`).pipe(
        HttpClientRequest.setUrlParams({
          package: options?.package as any,
          limit: options?.limit as any,
          offset: options?.offset as any,
        }),
        onRequest(['2xx']),
      ),
    'POST/-/npm/v1/hooks/hook': options =>
      HttpClientRequest.post(`/-/npm/v1/hooks/hook`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        onRequest(['2xx']),
      ),
    'GET/-/npm/v1/hooks/hook/{id}': id =>
      HttpClientRequest.get(`/-/npm/v1/hooks/hook/${id}`).pipe(
        onRequest(['2xx']),
      ),
    'PUT/-/npm/v1/hooks/hook/{id}': (id, options) =>
      HttpClientRequest.put(`/-/npm/v1/hooks/hook/${id}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        onRequest(['2xx']),
      ),
    'DELETE/-/npm/v1/hooks/hook/{id}': (id, options) =>
      HttpClientRequest.delete(`/-/npm/v1/hooks/hook/${id}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        onRequest(['2xx']),
      ),
  }
}

export interface Client {
  readonly httpClient: HttpClient.HttpClient
  /**
   * Get registry metadata info
   */
  readonly 'GET/': () => Effect.Effect<
    RegistryMetadata,
    HttpClientError.HttpClientError
  >
  /**
   * Get registry metadata info
   */
  readonly 'GET/-/all': () => Effect.Effect<
    All200,
    HttpClientError.HttpClientError | ClientError<'NpmError', NpmError>
  >
  /**
   * This endpoint responds with the package metadata document, sometimes informally called a "packument" or "doc.json".
   */
  readonly 'GET/{packageName}': (
    packageName: string,
  ) => Effect.Effect<
    PackageMetadata,
    HttpClientError.HttpClientError | ClientError<'NpmError', NpmError>
  >
  /**
   * This endpoint responds with the package metadata document for a specific version.
   */
  readonly 'GET/{packageName}/{version}': (
    packageName: string,
    version: string,
  ) => Effect.Effect<
    PackageVersionMetadata,
    HttpClientError.HttpClientError | ClientError<'NpmError', NpmError>
  >
  /**
   * This endpoint responds with the search result.
   * Special search qualifiers can be provided in the full-text query:
   * - author:bcoe: Show/filter results in which bcoe is the author
   * - maintainer:bcoe: Show/filter results in which bcoe is qualifier as a maintainer
   * - keywords:batman: Show/filter results that have batman in the keywords
   *
   *   - separating multiple keywords with
   *
   *     - , acts like a logical OR
   *
   *     - + acts like a logical AND
   *
   *     - ,- can be used to exclude keywords
   *
   * - not:unstable: Exclude packages whose version is < 1.0.0
   * - not:insecure: Exclude packages that are insecure or have vulnerable dependencies (based on the nsp registry)
   * - is:unstable: Show/filter packages whose version is < 1.0.0
   * - is:insecure: Show/filter packages that are insecure or have vulnerable dependencies (based on the nsp registry)
   * - boost-exact:false: Do not boost exact matches, defaults to true
   * Note: the values of quality, popularity, and maintenance are normalized into a unit-vector provide values between 0 - 1 for each to modify weightings, e.g., to return results based solely on quality, set quality=1.0, maintenance=0.0, popularity=0.0.
   */
  readonly 'GET/-/v1/search': (
    options?: V1SearchParams | undefined,
  ) => Effect.Effect<SearchResults, HttpClientError.HttpClientError>
  /**
   * Gets the downloads per day for a given period for all packages.
   */
  readonly 'GET/downloads/point/{period}': (
    period: string,
  ) => Effect.Effect<RegistryDownloads, HttpClientError.HttpClientError>
  /**
   * Gets the downloads per day for a given period for a specific package.
   */
  readonly 'GET/downloads/point/{period}/{packageName}': (
    period: string,
    packageName: string,
  ) => Effect.Effect<PackageDownloads, HttpClientError.HttpClientError>
  /**
   * Gets the downloads per day for a given period for all packages.
   */
  readonly 'GET/downloads/range/{period}': (
    period: string,
  ) => Effect.Effect<DailyRegistryDownloads, HttpClientError.HttpClientError>
  /**
   * Gets the downloads per day for a given period for a specific package.
   */
  readonly 'GET/downloads/range/{period}/{packageName}': (
    period: string,
    packageName: string,
  ) => Effect.Effect<DailyPackageDownloads, HttpClientError.HttpClientError>
  /**
   * Download count for specific versions of a package. It's only available for the previous 7 days.
   * Note: for scoped packages, the `/` needs to be percent encoded. (`@slack/client` -> `@slack%2Fclient`).
   */
  readonly 'GET/versions/{packageName}/last-week': (
    packageName: string,
  ) => Effect.Effect<
    PackageVersionsDownloadCount,
    HttpClientError.HttpClientError
  >
  /**
   * User login endpoint
   */
  readonly 'PUT/-/user/org.couchdb.user:{user}': (
    user: string,
    options: {
      readonly params?: UserOrgCouchdbUserUserParams | undefined
      readonly payload: LoginRequest
    },
  ) => Effect.Effect<
    LoginResponse,
    HttpClientError.HttpClientError | ClientError<'LegacyStatus', LegacyStatus>
  >
  /**
   * User detail endpoint
   */
  readonly 'GET/-/npm/v1/user': () => Effect.Effect<
    Profile,
    HttpClientError.HttpClientError
  >
  /**
   * User login endpoint
   */
  readonly 'POST/-/npm/v1/user': (options: {
    readonly params?: NpmV1UserParams | undefined
    readonly payload: ProfileUpdateRequest
  }) => Effect.Effect<Profile, HttpClientError.HttpClientError>
  /**
   * User's token list endpoint
   */
  readonly 'GET/-/npm/v1/tokens': () => Effect.Effect<
    TokenPage,
    HttpClientError.HttpClientError
  >
  /**
   * Token create endpoint
   */
  readonly 'POST/-/npm/v1/tokens': (options: {
    readonly params?: NpmV1TokensParams | undefined
    readonly payload: TokenCreationRequest
  }) => Effect.Effect<Token, HttpClientError.HttpClientError>
  /**
   * Token delete endpoint
   */
  readonly 'DELETE/-/npm/v1/tokens/token/{uuid}': (
    uuid: string,
    options?: NpmV1TokensTokenUuidParams | undefined,
  ) => Effect.Effect<void, HttpClientError.HttpClientError>
  /**
   * Token delete endpoint
   */
  readonly 'DELETE/-/user/token/{token}': (
    token: string,
    options?: UserTokenTokenParams | undefined,
  ) => Effect.Effect<LegacyStatus, HttpClientError.HttpClientError>
  /**
   * Hook list endpoint.
   */
  readonly 'GET/-/npm/v1/hooks': (
    options?: NpmV1HooksParams | undefined,
  ) => Effect.Effect<HookSearchResults, HttpClientError.HttpClientError>
  /**
   * Hook create endpoint.
   */
  readonly 'POST/-/npm/v1/hooks/hook': (options: {
    readonly params?: NpmV1HooksHookParams | undefined
    readonly payload: HookCreateRequest
  }) => Effect.Effect<Hook, HttpClientError.HttpClientError>
  /**
   * Get Hook endpoint.
   */
  readonly 'GET/-/npm/v1/hooks/hook/{id}': (
    id: string,
  ) => Effect.Effect<Hook, HttpClientError.HttpClientError>
  /**
   * Hook update endpoint
   */
  readonly 'PUT/-/npm/v1/hooks/hook/{id}': (
    id: string,
    options: {
      readonly params?: NpmV1HooksHookIdParams | undefined
      readonly payload: HookUpdateRequest
    },
  ) => Effect.Effect<Hook, HttpClientError.HttpClientError>
  /**
   * Hook delete endpoint
   */
  readonly 'DELETE/-/npm/v1/hooks/hook/{id}': (
    id: string,
    options?: NpmV1HooksHookIdParams | undefined,
  ) => Effect.Effect<Hook, HttpClientError.HttpClientError>
}

export interface ClientError<Tag extends string, E> extends Error {
  readonly _tag: Tag
  readonly request: HttpClientRequest.HttpClientRequest
  readonly response: HttpClientResponse.HttpClientResponse
  readonly data: E
  readonly message: string
}

class ClientErrorImpl extends Data.Error<{
  _tag: string
  data: any
  message: string
  request: HttpClientRequest.HttpClientRequest
  response: HttpClientResponse.HttpClientResponse
}> {
  override name = 'ClientError'
}

export const ClientError = <Tag extends string, E>(
  tag: Tag,
  data: E,
  response: HttpClientResponse.HttpClientResponse,
): ClientError<Tag, E> =>
  new ClientErrorImpl({
    _tag: tag,
    data,
    message: JSON.stringify(data),
    response,
    request: response.request,
  }) as any
