import type * as HttpClient from '@effect/platform/HttpClient'
import * as HttpClientError from '@effect/platform/HttpClientError'
import * as HttpClientRequest from '@effect/platform/HttpClientRequest'
import * as HttpClientResponse from '@effect/platform/HttpClientResponse'
import * as Data from 'effect/Data'
import * as Effect from 'effect/Effect'
import type { ParseError } from 'effect/ParseResult'
import * as Schema from 'effect/Schema'

export class RegistryMetadataOther extends Schema.Class<RegistryMetadataOther>(
  'RegistryMetadataOther',
)({
  data_size: Schema.Number,
}) {}

export class RegistryMetadataSizes extends Schema.Class<RegistryMetadataSizes>(
  'RegistryMetadataSizes',
)({
  external: Schema.Number,
  file: Schema.Number,
  active: Schema.Number,
}) {}

/**
 * Registry Metadata
 */
export class RegistryMetadata extends Schema.Class<RegistryMetadata>(
  'RegistryMetadata',
)({
  data_size: Schema.Number,
  doc_count: Schema.Int,
  other: RegistryMetadataOther,
  update_seq: Schema.Number,
  disk_size: Schema.Number,
  disk_format_version: Schema.Int,
  doc_del_count: Schema.Int,
  uuid: Schema.String,
  instance_start_time: Schema.String,
  committed_update_seq: Schema.Int,
  compacted_seq: Schema.Int,
  db_name: Schema.String,
  purge_seq: Schema.Int,
  sizes: RegistryMetadataSizes,
  engine: Schema.String,
}) {}

export class All200 extends Schema.Array(
  Schema.Record({ key: Schema.String, value: Schema.Unknown }),
) {}

/**
 * Generic NpmError
 */
export class NpmError extends Schema.Class<NpmError>('NpmError')({
  /**
   * Error message
   */
  error: Schema.optionalWith(Schema.String, { nullable: true }),
  code: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Error message
   */
  message: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * HTTP Status Code
   */
  statusCode: Schema.optionalWith(Schema.Int, { nullable: true }),
}) {}

/**
 * A mapping of dist tags to the versions they point to.
 */
export class DistTags extends Schema.Class<DistTags>('DistTags')({
  /**
   * Latest version number
   */
  latest: Schema.String,
}) {}

/**
 * An object mapping versions to the time published, along with created and modified timestamps.
 */
export class VersionsToTimestamps extends Schema.Class<VersionsToTimestamps>(
  'VersionsToTimestamps',
)({
  /**
   * ISO string of when the package was created.
   */
  created: Schema.String,
  /**
   * ISO string of the last time this package was modified.
   */
  modified: Schema.String,
}) {}

/**
 * Represents a person associated to a package. It has at least one of the following fields defined:
 * - name: a freeform string name
 * - email: an email address
 * - url: a url for a web page with more information about the author
 * Historically no validation has been performed on those fields; they are generated by parsing user-provided data in package.json at publication time.
 */
export class Person extends Schema.Class<Person>('Person')({
  /**
   * A freeform string name
   */
  name: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * An email address
   */
  email: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * A url for a web page with more information about the author
   */
  url: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * It represents the bug tracking methods.
 */
export class BugTracker extends Schema.Class<BugTracker>('BugTracker')({
  /**
   * The url of the project's issue tracker.
   */
  url: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The email address to which issues should be reported.
   */
  email: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * An object specifying the repository where the source for this package might be found.
 */
export class Repository extends Schema.Class<Repository>('Repository')({
  /**
   * Repository type (for example, `git`)
   */
  type: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Url of the repository
   */
  url: Schema.String,
  /**
   * Specific directory in the repository containing the package (for example, a directory in a monorepo)
   */
  directory: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * Package metadata describes a package for its consumers: who wrote it, where its repository is, and what versions of it have been published. It also contains a description of each version of a package present in the registry, listing its dependencies, giving the url of its tarball, and so on. Package metadata is useful for finding packages and for installing them.
 */
export class PackageMetadata extends Schema.Class<PackageMetadata>(
  'PackageMetadata',
)({
  /**
   * The revision number of this version of the document in CouchDB.
   */
  _rev: Schema.String,
  /**
   * ISO string of the last time this package was modified.
   */
  modified: Schema.String,
  /**
   * Final and detailed search score values
   */
  'dist-tags': DistTags,
  /**
   * A mapping of version numbers to objects containing the information needed to install that version.
   */
  versions: Schema.Record({ key: Schema.String, value: Schema.Unknown }),
  /**
   * Mapping of version numbers to publishing timestamps
   */
  time: VersionsToTimestamps,
  /**
   * An object whose keys are the npm user names of people who have starred the package.
   */
  users: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * The package name, used as an ID in CouchDB
   */
  _id: Schema.String,
  /**
   * The package name
   */
  name: Schema.String,
  author: Schema.optionalWith(Person, { nullable: true }),
  /**
   * Bug tracker
   */
  bugs: Schema.optionalWith(BugTracker, { nullable: true }),
  /**
   * List of package contributors
   */
  contributors: Schema.optionalWith(Schema.Array(Person), { nullable: true }),
  /**
   * A short description of the package
   */
  description: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The url of the project homepage.
   */
  homepage: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Array of string keywords
   */
  keywords: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * The SPDX identifier of the package's license
   */
  license: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  maintainers: Schema.optionalWith(Schema.Array(Person), { nullable: true }),
  /**
   * The first 64K of the README data for the most-recently published version of the package
   */
  readme: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The name of the file from which the readme data was taken.
   */
  readmeFilename: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Repository containing the package's source
   */
  repository: Schema.optionalWith(Repository, { nullable: true }),
}) {}

/**
 * The dist object is generated by npm and may be relied upon. Each dist object has at least two fields:
 * - tarball: the url of the tarball containing the payload for this package
 * - shasum: the SHA-1 sum of the tarball
 * - integrity: since Apr 2017, string in the format `<hashAlgorithm>-<base64-hash>`, refer the Subresource Integrity and cacache package for more
 * - fileCount: since Feb 2018, the number of files in the tarball, folder excluded
 * - unpackedSize: since Feb 2018, the total byte of the unpacked files in the tarball
 * - npm-signature: since Apr 2018, a PGP signature of `<package>@<version>:<integrity>`, refer the npm blog and doc for more (in the future) a SHA-2 512 sum of the tarball
 */
export class DistInfo extends Schema.Class<DistInfo>('DistInfo')({
  /**
   * The url of the tarball containing the payload for this package
   */
  tarball: Schema.String,
  /**
   * The SHA-1 sum of the tarball
   */
  shasum: Schema.String,
  /**
   * Since Apr 2017, string in the format `<hashAlgorithm>-<base64-hash>`, refer the Subresource Integrity and cacache package for more
   */
  integrity: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Since Feb 2018, the number of files in the tarball, folder excluded
   */
  fileCount: Schema.optionalWith(Schema.Int, { nullable: true }),
  /**
   * Since Feb 2018, the total byte of the unpacked files in the tarball
   */
  unpackedSize: Schema.optionalWith(Schema.Int, { nullable: true }),
  /**
   * PGP signature of `<package>@<version>:<integrity>`
   */
  'npm-signature': Schema.optionalWith(Schema.String, { nullable: true }),
  signatures: Schema.optionalWith(
    Schema.Array(
      Schema.Struct({
        keyid: Schema.String,
        sig: Schema.String,
      }),
    ),
    { nullable: true },
  ),
}) {}

/**
 * An object specifying the funding info for this package.
 */
export class Funding extends Schema.Class<Funding>('Funding')({
  /**
   * Funding type
   */
  type: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Url of the funding
   */
  url: Schema.String,
}) {}

/**
 * Internal npm data
 */
export class NpmOperationalInternal extends Schema.Class<NpmOperationalInternal>(
  'NpmOperationalInternal',
)({
  host: Schema.String,
  tmp: Schema.String,
}) {}

/**
 * Objects containing the information needed to install that version
 */
export class PackageVersionMetadata extends Schema.Class<PackageVersionMetadata>(
  'PackageVersionMetadata',
)({
  /**
   * The version string for this version
   */
  version: Schema.String,
  /**
   * The deprecation warnings message of this version
   */
  deprecated: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * A mapping of other packages this version depends on to the required semver ranges
   */
  dependencies: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * An object mapping package names to the required semver ranges of optional dependencies
   */
  optionalDependencies: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    { nullable: true },
  ),
  /**
   * A mapping of package names to the required semver ranges of development dependencies
   */
  devDependencies: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    { nullable: true },
  ),
  /**
   * An array of dependencies bundled with this version
   */
  bundleDependencies: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * A mapping of package names to the required semver ranges of development dependencies
   */
  peerDependencies: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    { nullable: true },
  ),
  /**
   * A mapping of dependency package names to be replaced with another version, or another package entirely
   */
  overrides: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * A mapping of bin commands to set up for this version
   */
  bin: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * An array of directories included by this version
   */
  directories: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  dist: DistInfo,
  engines: Schema.optionalWith(
    Schema.Struct({
      /**
       * The node engines required for this version to run, if specified
       */
      node: Schema.optionalWith(Schema.String, { nullable: true }),
      /**
       * The npm engines required for this version to run, if specified
       */
      npm: Schema.optionalWith(Schema.String, { nullable: true }),
    }),
    { nullable: true },
  ),
  /**
   * `true` if this version is known to have a shrinkwrap that must be used to install it; false if this version is known not to have a shrinkwrap. If this field is `undefined`, the client must determine through other means if a shrinkwrap exists.
   */
  _hasShrinkwrap: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  /**
   * The version of node used to publish the package
   */
  _nodeVersion: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * User who published this package version
   */
  _npmUser: Person,
  /**
   * The version of the npm client used to publish the package
   */
  _npmVersion: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Commit hash corresponding to the published version
   */
  gitHead: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The package's entry point (e.g., index.js or main.js)
   */
  main: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The package's entry point (e.g., index.js or main.js) if the module is meant to be used client-side
   */
  browser: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The "scripts" property is a dictionary containing script commands that are run at various times in the lifecycle of your package. The key is the lifecycle event, and the value is the command to run at that point.
   */
  scripts: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * A "config" object can be used to set configuration parameters used in package scripts that persist across upgrades.
   */
  config: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  /**
   * A set of config values that will be used at publish-time
   */
  publishConfig: Schema.optionalWith(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    {
      nullable: true,
    },
  ),
  funding: Schema.optionalWith(Funding, { nullable: true }),
  /**
   * An array of file patterns that describes the entries to be included when the package is installed as a dependency.
   */
  files: Schema.optionalWith(Schema.Array(Schema.String), { nullable: true }),
  /**
   * An array of operating systems the package will run on
   */
  os: Schema.optionalWith(Schema.Array(Schema.String), { nullable: true }),
  /**
   * If the package code only runs on certain cpu architectures
   */
  cpu: Schema.optionalWith(Schema.Array(Schema.String), { nullable: true }),
  /**
   * If the package is private or not
   */
  private: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  /**
   * An array of file patterns that describes locations within the local file system that the install client should look up to find each workspace that needs to be symlinked to the top level node_modules folder.
   */
  workspaces: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * Internal npm data
   */
  _npmOperationalInternal: Schema.optionalWith(NpmOperationalInternal, {
    nullable: true,
  }),
  /**
   * The package name, used as an ID in CouchDB
   */
  _id: Schema.String,
  /**
   * The package name
   */
  name: Schema.String,
  author: Schema.optionalWith(Person, { nullable: true }),
  /**
   * Bug tracker
   */
  bugs: Schema.optionalWith(BugTracker, { nullable: true }),
  /**
   * List of package contributors
   */
  contributors: Schema.optionalWith(Schema.Array(Person), { nullable: true }),
  /**
   * A short description of the package
   */
  description: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The url of the project homepage.
   */
  homepage: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Array of string keywords
   */
  keywords: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * The SPDX identifier of the package's license
   */
  license: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  maintainers: Schema.optionalWith(Schema.Array(Person), { nullable: true }),
  /**
   * The first 64K of the README data for the most-recently published version of the package
   */
  readme: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The name of the file from which the readme data was taken.
   */
  readmeFilename: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Repository containing the package's source
   */
  repository: Schema.optionalWith(Repository, { nullable: true }),
}) {}

export class V1SearchParams extends Schema.Struct({
  text: Schema.optionalWith(Schema.String, { nullable: true }),
  size: Schema.optionalWith(
    Schema.Int.pipe(
      Schema.greaterThanOrEqualTo(-1),
      Schema.lessThanOrEqualTo(250),
    ),
    { nullable: true },
  ),
  from: Schema.optionalWith(Schema.Int.pipe(Schema.greaterThanOrEqualTo(-1)), {
    nullable: true,
  }),
  quality: Schema.optionalWith(Schema.Number, { nullable: true }),
  popularity: Schema.optionalWith(Schema.Number, { nullable: true }),
  maintenance: Schema.optionalWith(Schema.Number, { nullable: true }),
}) {}

/**
 * It contains a collection of links of pages associated to the package.
 */
export class PackageLinks extends Schema.Class<PackageLinks>('PackageLinks')({
  /**
   * The NPM url of the package
   */
  npm: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The url of the project homepage.
   */
  homepage: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The url of the project repository.
   */
  repository: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * The url of the project's issue tracker and / or the email address to which issues should be reported.
   */
  bugs: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * It contains abbreviated package metadata returned by searching the registry for packages.
 */
export class PackageSearchResult extends Schema.Class<PackageSearchResult>(
  'PackageSearchResult',
)({
  /**
   * The package name
   */
  name: Schema.String,
  /**
   * Latest package version number
   */
  version: Schema.String,
  /**
   * The scope of the package
   */
  scope: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * A short description of the package
   */
  description: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Array of string keywords
   */
  keywords: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * Publishing timestamp for the latest version
   */
  date: Schema.String,
  /**
   * Links for pages associated to the package
   */
  links: PackageLinks,
  /**
   * The package publisher
   */
  publisher: Person,
  /**
   * The package author
   */
  author: Schema.optionalWith(Person, { nullable: true }),
  /**
   * Array of person objects for people with permission to publish this package; not authoritative but informational
   */
  maintainers: Schema.optionalWith(Schema.Array(Person), { nullable: true }),
}) {}

/**
 * It contains the search score values for the quality, popularity and maintenance categories.
 */
export class SearchScoreDetail extends Schema.Class<SearchScoreDetail>(
  'SearchScoreDetail',
)({
  /**
   * Package quality score value
   */
  quality: Schema.Number,
  /**
   * Package popularity score value
   */
  popularity: Schema.Number,
  /**
   * Package maintenance score value
   */
  maintenance: Schema.Number,
}) {}

/**
 * It contains the final and detailed search score values.
 */
export class SearchScore extends Schema.Class<SearchScore>('SearchScore')({
  /**
   * Final search score value, computed from the detailed scores
   */
  final: Schema.Number,
  /**
   * Detailed search score values
   */
  detail: SearchScoreDetail,
}) {}

/**
 * It contains flag attributes categorizing the package.
 */
export class PackageFlags extends Schema.Class<PackageFlags>('PackageFlags')({
  /**
   * If true, package version is `<1.0.0`
   */
  unstable: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  /**
   * If true, package is insecure or has vulnerable dependencies
   */
  insecure: Schema.optionalWith(Schema.Boolean, { nullable: true }),
}) {}

/**
 * It contains the search result for a single package and its search score.
 */
export class SearchResult extends Schema.Class<SearchResult>('SearchResult')({
  /**
   * Abbreviated package metadata
   */
  package: PackageSearchResult,
  /**
   * Final and detailed search score values
   */
  score: Schema.optionalWith(SearchScore, { nullable: true }),
  /**
   * Search score value; may be different from `score.final`
   */
  searchScore: Schema.Number,
  /**
   * Flag attributes for the package
   */
  flags: Schema.optionalWith(PackageFlags, { nullable: true }),
}) {}

/**
 * It contains the results returned by the registry for a query.
 */
export class SearchResults extends Schema.Class<SearchResults>('SearchResults')(
  {
    objects: Schema.Array(SearchResult),
    /**
     * Total number of search results corresponding to a query; may be higher than the number of `objects`
     */
    total: Schema.Int,
    /**
     * Date at which the search happened
     */
    time: Schema.String,
  },
) {}

/**
 * Lists the number of downloads for the registry in a given time period.
 */
export class RegistryDownloads extends Schema.Class<RegistryDownloads>(
  'RegistryDownloads',
)({
  /**
   * Total number of downloads
   */
  downloads: Schema.Int,
  /**
   * Date of the first day (inclusive)
   */
  start: Schema.String,
  /**
   * Date of the last day (inclusive)
   */
  end: Schema.String,
}) {}

/**
 * Lists the number of downloads for a package in a given time period.
 */
export class PackageDownloads extends Schema.Class<PackageDownloads>(
  'PackageDownloads',
)({
  /**
   * Package name
   */
  package: Schema.String,
  /**
   * Total number of downloads
   */
  downloads: Schema.Int,
  /**
   * Date of the first day (inclusive)
   */
  start: Schema.String,
  /**
   * Date of the last day (inclusive)
   */
  end: Schema.String,
}) {}

/**
 * Lists the number of downloads in a given day.
 */
export class DownloadsPerDay extends Schema.Class<DownloadsPerDay>(
  'DownloadsPerDay',
)({
  downloads: Schema.Int,
  day: Schema.String,
}) {}

/**
 * Lists the number of downloads for a package for each day in a given time period.
 */
export class DailyRegistryDownloads extends Schema.Class<DailyRegistryDownloads>(
  'DailyRegistryDownloads',
)({
  /**
   * Download counts per day
   */
  downloads: Schema.Array(DownloadsPerDay),
  /**
   * Date of the first day (inclusive)
   */
  start: Schema.String,
  /**
   * Date of the last day (inclusive)
   */
  end: Schema.String,
}) {}

/**
 * Lists the number of downloads for a package for each day in a given time period.
 */
export class DailyPackageDownloads extends Schema.Class<DailyPackageDownloads>(
  'DailyPackageDownloads',
)({
  /**
   * Package name
   */
  package: Schema.String,
  /**
   * Download counts per day
   */
  downloads: Schema.Array(DownloadsPerDay),
  /**
   * Date of the first day (inclusive)
   */
  start: Schema.String,
  /**
   * Date of the last day (inclusive)
   */
  end: Schema.String,
}) {}

/**
 * Package download count for specific versions.
 */
export class PackageVersionsDownloadCount extends Schema.Class<PackageVersionsDownloadCount>(
  'PackageVersionsDownloadCount',
)({
  /**
   * Package name
   */
  package: Schema.String,
  /**
   * A map containing the package version as key and the download count as value.
   */
  downloads: Schema.Record({ key: Schema.String, value: Schema.Unknown }),
}) {}

export class UserOrgCouchdbUserUserParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class LoginRequest extends Schema.Class<LoginRequest>('LoginRequest')({
  /**
   * NPM username.
   */
  name: Schema.String,
  /**
   * NPM user password.
   */
  password: Schema.String,
  readonly: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  cidr_whitelist: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
}) {}

export class LoginResponse extends Schema.Class<LoginResponse>('LoginResponse')(
  {
    /**
     * Bearer token
     */
    token: Schema.optionalWith(Schema.String, { nullable: true }),
    /**
     * If login succeded
     */
    ok: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  },
) {}

export class LegacyStatus extends Schema.Class<LegacyStatus>('LegacyStatus')({
  /**
   * If operation succeded.
   */
  ok: Schema.Boolean,
}) {}

export class Profile extends Schema.Class<Profile>('Profile')({
  /**
   * User name
   */
  name: Schema.String,
  /**
   * User email
   */
  email: Schema.String,
  /**
   * Email verification status
   */
  email_verified: Schema.Boolean,
  /**
   * When the account was created
   */
  created: Schema.String,
  /**
   * When the account was updated
   */
  updated: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * CIDR whitelist
   */
  cidr_whitelist: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  /**
   * User full name
   */
  fullname: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * User homepage url
   */
  homepage: Schema.optionalWith(Schema.String, { nullable: true }),
  freenode: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Twitter username
   */
  twitter: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * GitHub username
   */
  github: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class NpmV1UserParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class PasswordUpdateRequest extends Schema.Class<PasswordUpdateRequest>(
  'PasswordUpdateRequest',
)({
  old: Schema.String,
  'new': Schema.String,
}) {}

export class ProfileUpdateRequest extends Schema.Class<ProfileUpdateRequest>(
  'ProfileUpdateRequest',
)({
  /**
   * Password change request data
   */
  password: Schema.optionalWith(PasswordUpdateRequest, { nullable: true }),
  /**
   * User email
   */
  email: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * User full name
   */
  fullname: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * User homepage url
   */
  homepage: Schema.optionalWith(Schema.String, { nullable: true }),
  freenode: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Twitter username
   */
  twitter: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * GitHub username
   */
  github: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * Urls to navigate results
 */
export class PageUrls extends Schema.Class<PageUrls>('PageUrls')({
  /**
   * Url of the next results
   */
  next: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Url of the previous results
   */
  prev: Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * Objects containing the list of user's tokens
 */
export class TokenPage extends Schema.Class<TokenPage>('TokenPage')({
  userHasOldFormatToken: Schema.Boolean,
  /**
   * Number of total items
   */
  total: Schema.optionalWith(Schema.Int, { nullable: true }),
  objects: Schema.Array(
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
  ),
  /**
   * Urls to navigate results
   */
  urls: PageUrls,
}) {}

export class NpmV1TokensParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class TokenCreationRequest extends Schema.Class<TokenCreationRequest>(
  'TokenCreationRequest',
)({
  /**
   * NPM User password
   */
  password: Schema.String,
  readonly: Schema.optionalWith(Schema.Boolean, { nullable: true }),
  cidr_whitelist: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
}) {}

export class Token extends Schema.Class<Token>('Token')({
  /**
   * \[REDACTED\] on subsequent display. The "Bearer" token.
   */
  token: Schema.String,
  /**
   * sha512 hash of the token UUID
   */
  key: Schema.String,
  automation: Schema.Boolean,
  cidr_whitelist: Schema.optionalWith(Schema.Array(Schema.String), {
    nullable: true,
  }),
  created: Schema.String,
  updated: Schema.String,
  readonly: Schema.Boolean,
}) {}

export class NpmV1TokensTokenUuidParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class UserTokenTokenParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

export class NpmV1HooksParams extends Schema.Struct({
  package: Schema.optionalWith(Schema.String, { nullable: true }),
  limit: Schema.optionalWith(Schema.Int, { nullable: true }),
  offset: Schema.optionalWith(Schema.Int, { nullable: true }),
}) {}

/**
 * Type of object being watched; `package`, `scope`, or `owner`.
 */
export class HookType extends Schema.Literal('package', 'scope', 'owner') {}

/**
 * Hook object
 */
export class Hook extends Schema.Class<Hook>('Hook')({
  /**
   * Hook id
   */
  id: Schema.String,
  /**
   * NPM user name.
   */
  username: Schema.String,
  /**
   * Name of package or organization/user scope to watch, e.g, `@scope` or `package`.
   */
  name: Schema.String,
  /**
   * Full uri of the endpoint to post the notification to.
   */
  endpoint: Schema.String,
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  secret: Schema.String,
  type: HookType,
  /**
   * Hook creation date
   */
  created: Schema.String,
  /**
   * Hook update date
   */
  updated: Schema.String,
  delivered: Schema.Boolean,
  /**
   * Hook last delivery date
   */
  last_delivery: Schema.optionalWith(Schema.String, { nullable: true }),
  /**
   * Response code
   */
  response_code: Schema.Int,
  /**
   * Hook status
   */
  status: Schema.String,
  /**
   * If the Hook has been deleted
   */
  deleted: Schema.optionalWith(Schema.Boolean, { nullable: true }),
}) {}

/**
 * It contains the results returned by the hook search.
 */
export class HookSearchResults extends Schema.Class<HookSearchResults>(
  'HookSearchResults',
)({
  objects: Schema.Array(Hook),
  /**
   * Total number of search results corresponding to a query; may be higher than the number of `objects`
   */
  total: Schema.Int,
}) {}

export class NpmV1HooksHookParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * Hook creation request object
 */
export class HookCreateRequest extends Schema.Class<HookCreateRequest>(
  'HookCreateRequest',
)({
  type: HookType,
  /**
   * Name of package or organization/user scope to watch, e.g, `@scope` or `package`.
   */
  name: Schema.String,
  /**
   * Full uri of the endpoint to post the notification to.
   */
  endpoint: Schema.String,
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  secret: Schema.String,
}) {}

export class NpmV1HooksHookIdParams extends Schema.Struct({
  'npm-otp': Schema.optionalWith(Schema.String, { nullable: true }),
}) {}

/**
 * Hook update request object
 */
export class HookUpdateRequest extends Schema.Class<HookUpdateRequest>(
  'HookUpdateRequest',
)({
  /**
   * Full uri of the endpoint to post the notification to.
   */
  endpoint: Schema.String,
  /**
   * A secret shared between the registry & you; used to sign the payload.
   */
  secret: Schema.String,
}) {}

export const make = (
  httpClient: HttpClient.HttpClient,
  options: {
    readonly transformClient?:
      | ((
          client: HttpClient.HttpClient,
        ) => Effect.Effect<HttpClient.HttpClient>)
      | undefined
  } = {},
): NPM => {
  const unexpectedStatus = (response: HttpClientResponse.HttpClientResponse) =>
    Effect.flatMap(
      Effect.orElseSucceed(response.json, () => 'Unexpected status code'),
      description =>
        Effect.fail(
          new HttpClientError.ResponseError({
            request: response.request,
            response,
            reason: 'StatusCode',
            description:
              typeof description === 'string'
                ? description
                : JSON.stringify(description),
          }),
        ),
    )
  const withResponse: <A, E>(
    f: (response: HttpClientResponse.HttpClientResponse) => Effect.Effect<A, E>,
  ) => (
    request: HttpClientRequest.HttpClientRequest,
  ) => Effect.Effect<any, any> = options.transformClient
    ? f => request =>
        Effect.flatMap(
          Effect.flatMap(options.transformClient!(httpClient), client =>
            client.execute(request),
          ),
          f,
        )
    : f => request => Effect.flatMap(httpClient.execute(request), f)
  const decodeSuccess =
    <A, I, R>(schema: Schema.Schema<A, I, R>) =>
    (response: HttpClientResponse.HttpClientResponse) =>
      HttpClientResponse.schemaBodyJson(schema)(response)
  const decodeError =
    <const Tag extends string, A, I, R>(
      tag: Tag,
      schema: Schema.Schema<A, I, R>,
    ) =>
    (response: HttpClientResponse.HttpClientResponse) =>
      Effect.flatMap(
        HttpClientResponse.schemaBodyJson(schema)(response),
        cause => Effect.fail(NPMError(tag, cause, response)),
      )
  return {
    httpClient,
    'GET/': () =>
      HttpClientRequest.get(`/`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(RegistryMetadata),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/all': () =>
      HttpClientRequest.get(`/-/all`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(All200),
            '404': decodeError('NpmError', NpmError),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/{packageName}': packageName =>
      HttpClientRequest.get(`/${packageName}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(PackageMetadata),
            '404': decodeError('NpmError', NpmError),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/{packageName}/{version}': (packageName, version) =>
      HttpClientRequest.get(`/${packageName}/${version}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(PackageVersionMetadata),
            '404': decodeError('NpmError', NpmError),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/v1/search': options =>
      HttpClientRequest.get(`/-/v1/search`).pipe(
        HttpClientRequest.setUrlParams({
          text: options?.['text'] as any,
          size: options?.['size'] as any,
          from: options?.['from'] as any,
          quality: options?.['quality'] as any,
          popularity: options?.['popularity'] as any,
          maintenance: options?.['maintenance'] as any,
        }),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(SearchResults),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/downloads/point/{period}': period =>
      HttpClientRequest.get(`/downloads/point/${period}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(RegistryDownloads),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/downloads/point/{period}/{packageName}': (period, packageName) =>
      HttpClientRequest.get(`/downloads/point/${period}/${packageName}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(PackageDownloads),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/downloads/range/{period}': period =>
      HttpClientRequest.get(`/downloads/range/${period}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(DailyRegistryDownloads),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/downloads/range/{period}/{packageName}': (period, packageName) =>
      HttpClientRequest.get(`/downloads/range/${period}/${packageName}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(DailyPackageDownloads),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/versions/{packageName}/last-week': packageName =>
      HttpClientRequest.get(`/versions/${packageName}/last-week`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(PackageVersionsDownloadCount),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'PUT/-/user/org.couchdb.user:{user}': (user, options) =>
      HttpClientRequest.put(`/-/user/org.couchdb.user:${user}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyUnsafeJson(options.payload),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(LoginResponse),
            '401': decodeError('LegacyStatus', LegacyStatus),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/npm/v1/user': () =>
      HttpClientRequest.get(`/-/npm/v1/user`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Profile),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'POST/-/npm/v1/user': options =>
      HttpClientRequest.post(`/-/npm/v1/user`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyUnsafeJson(options.payload),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Profile),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/npm/v1/tokens': () =>
      HttpClientRequest.get(`/-/npm/v1/tokens`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(TokenPage),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'POST/-/npm/v1/tokens': options =>
      HttpClientRequest.post(`/-/npm/v1/tokens`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyUnsafeJson(options.payload),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Token),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'DELETE/-/npm/v1/tokens/token/{uuid}': (uuid, options) =>
      HttpClientRequest.del(`/-/npm/v1/tokens/token/${uuid}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        withResponse(
          HttpClientResponse.matchStatus({
            '204': () => Effect.void,
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'DELETE/-/user/token/{token}': (token, options) =>
      HttpClientRequest.del(`/-/user/token/${token}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(LegacyStatus),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/npm/v1/hooks': options =>
      HttpClientRequest.get(`/-/npm/v1/hooks`).pipe(
        HttpClientRequest.setUrlParams({
          package: options?.['package'] as any,
          limit: options?.['limit'] as any,
          offset: options?.['offset'] as any,
        }),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(HookSearchResults),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'POST/-/npm/v1/hooks/hook': options =>
      HttpClientRequest.post(`/-/npm/v1/hooks/hook`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyUnsafeJson(options.payload),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Hook),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'GET/-/npm/v1/hooks/hook/{id}': id =>
      HttpClientRequest.get(`/-/npm/v1/hooks/hook/${id}`).pipe(
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Hook),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'PUT/-/npm/v1/hooks/hook/{id}': (id, options) =>
      HttpClientRequest.put(`/-/npm/v1/hooks/hook/${id}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options.params?.['npm-otp'] ?? undefined,
        }),
        HttpClientRequest.bodyUnsafeJson(options.payload),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Hook),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    'DELETE/-/npm/v1/hooks/hook/{id}': (id, options) =>
      HttpClientRequest.del(`/-/npm/v1/hooks/hook/${id}`).pipe(
        HttpClientRequest.setHeaders({
          'npm-otp': options?.['npm-otp'] ?? undefined,
        }),
        withResponse(
          HttpClientResponse.matchStatus({
            '2xx': decodeSuccess(Hook),
            orElse: unexpectedStatus,
          }),
        ),
      ),
  }
}

export interface NPM {
  readonly httpClient: HttpClient.HttpClient
  /**
   * Get registry metadata info
   */
  readonly 'GET/': () => Effect.Effect<
    typeof RegistryMetadata.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Get registry metadata info
   */
  readonly 'GET/-/all': () => Effect.Effect<
    typeof All200.Type,
    | HttpClientError.HttpClientError
    | ParseError
    | NPMError<'NpmError', typeof NpmError.Type>
  >
  /**
   * This endpoint responds with the package metadata document, sometimes informally called a "packument" or "doc.json".
   */
  readonly 'GET/{packageName}': (
    packageName: string,
  ) => Effect.Effect<
    typeof PackageMetadata.Type,
    | HttpClientError.HttpClientError
    | ParseError
    | NPMError<'NpmError', typeof NpmError.Type>
  >
  /**
   * This endpoint responds with the package metadata document for a specific version.
   */
  readonly 'GET/{packageName}/{version}': (
    packageName: string,
    version: string,
  ) => Effect.Effect<
    typeof PackageVersionMetadata.Type,
    | HttpClientError.HttpClientError
    | ParseError
    | NPMError<'NpmError', typeof NpmError.Type>
  >
  /**
   * This endpoint responds with the search result.
   * Special search qualifiers can be provided in the full-text query:
   * - author:bcoe: Show/filter results in which bcoe is the author
   * - maintainer:bcoe: Show/filter results in which bcoe is qualifier as a maintainer
   * - keywords:batman: Show/filter results that have batman in the keywords
   *
   *   - separating multiple keywords with
   *
   *     - , acts like a logical OR
   *
   *     - + acts like a logical AND
   *
   *     - ,- can be used to exclude keywords
   *
   * - not:unstable: Exclude packages whose version is < 1.0.0
   * - not:insecure: Exclude packages that are insecure or have vulnerable dependencies (based on the nsp registry)
   * - is:unstable: Show/filter packages whose version is < 1.0.0
   * - is:insecure: Show/filter packages that are insecure or have vulnerable dependencies (based on the nsp registry)
   * - boost-exact:false: Do not boost exact matches, defaults to true
   * Note: the values of quality, popularity, and maintenance are normalized into a unit-vector provide values between 0 - 1 for each to modify weightings, e.g., to return results based solely on quality, set quality=1.0, maintenance=0.0, popularity=0.0.
   */
  readonly 'GET/-/v1/search': (
    options?: typeof V1SearchParams.Encoded | undefined,
  ) => Effect.Effect<
    typeof SearchResults.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Gets the downloads per day for a given period for all packages.
   */
  readonly 'GET/downloads/point/{period}': (
    period: string,
  ) => Effect.Effect<
    typeof RegistryDownloads.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Gets the downloads per day for a given period for a specific package.
   */
  readonly 'GET/downloads/point/{period}/{packageName}': (
    period: string,
    packageName: string,
  ) => Effect.Effect<
    typeof PackageDownloads.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Gets the downloads per day for a given period for all packages.
   */
  readonly 'GET/downloads/range/{period}': (
    period: string,
  ) => Effect.Effect<
    typeof DailyRegistryDownloads.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Gets the downloads per day for a given period for a specific package.
   */
  readonly 'GET/downloads/range/{period}/{packageName}': (
    period: string,
    packageName: string,
  ) => Effect.Effect<
    typeof DailyPackageDownloads.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Download count for specific versions of a package. It's only available for the previous 7 days.
   * Note: for scoped packages, the `/` needs to be percent encoded. (`@slack/client` -> `@slack%2Fclient`).
   */
  readonly 'GET/versions/{packageName}/last-week': (
    packageName: string,
  ) => Effect.Effect<
    typeof PackageVersionsDownloadCount.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * User login endpoint
   */
  readonly 'PUT/-/user/org.couchdb.user:{user}': (
    user: string,
    options: {
      readonly params?: typeof UserOrgCouchdbUserUserParams.Encoded | undefined
      readonly payload: typeof LoginRequest.Encoded
    },
  ) => Effect.Effect<
    typeof LoginResponse.Type,
    | HttpClientError.HttpClientError
    | ParseError
    | NPMError<'LegacyStatus', typeof LegacyStatus.Type>
  >
  /**
   * User detail endpoint
   */
  readonly 'GET/-/npm/v1/user': () => Effect.Effect<
    typeof Profile.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * User login endpoint
   */
  readonly 'POST/-/npm/v1/user': (options: {
    readonly params?: typeof NpmV1UserParams.Encoded | undefined
    readonly payload: typeof ProfileUpdateRequest.Encoded
  }) => Effect.Effect<
    typeof Profile.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * User's token list endpoint
   */
  readonly 'GET/-/npm/v1/tokens': () => Effect.Effect<
    typeof TokenPage.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Token create endpoint
   */
  readonly 'POST/-/npm/v1/tokens': (options: {
    readonly params?: typeof NpmV1TokensParams.Encoded | undefined
    readonly payload: typeof TokenCreationRequest.Encoded
  }) => Effect.Effect<
    typeof Token.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Token delete endpoint
   */
  readonly 'DELETE/-/npm/v1/tokens/token/{uuid}': (
    uuid: string,
    options?: typeof NpmV1TokensTokenUuidParams.Encoded | undefined,
  ) => Effect.Effect<void, HttpClientError.HttpClientError | ParseError>
  /**
   * Token delete endpoint
   */
  readonly 'DELETE/-/user/token/{token}': (
    token: string,
    options?: typeof UserTokenTokenParams.Encoded | undefined,
  ) => Effect.Effect<
    typeof LegacyStatus.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Hook list endpoint.
   */
  readonly 'GET/-/npm/v1/hooks': (
    options?: typeof NpmV1HooksParams.Encoded | undefined,
  ) => Effect.Effect<
    typeof HookSearchResults.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Hook create endpoint.
   */
  readonly 'POST/-/npm/v1/hooks/hook': (options: {
    readonly params?: typeof NpmV1HooksHookParams.Encoded | undefined
    readonly payload: typeof HookCreateRequest.Encoded
  }) => Effect.Effect<
    typeof Hook.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Get Hook endpoint.
   */
  readonly 'GET/-/npm/v1/hooks/hook/{id}': (
    id: string,
  ) => Effect.Effect<
    typeof Hook.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Hook update endpoint
   */
  readonly 'PUT/-/npm/v1/hooks/hook/{id}': (
    id: string,
    options: {
      readonly params?: typeof NpmV1HooksHookIdParams.Encoded | undefined
      readonly payload: typeof HookUpdateRequest.Encoded
    },
  ) => Effect.Effect<
    typeof Hook.Type,
    HttpClientError.HttpClientError | ParseError
  >
  /**
   * Hook delete endpoint
   */
  readonly 'DELETE/-/npm/v1/hooks/hook/{id}': (
    id: string,
    options?: typeof NpmV1HooksHookIdParams.Encoded | undefined,
  ) => Effect.Effect<
    typeof Hook.Type,
    HttpClientError.HttpClientError | ParseError
  >
}

export interface NPMError<Tag extends string, E> {
  readonly _tag: Tag
  readonly request: HttpClientRequest.HttpClientRequest
  readonly response: HttpClientResponse.HttpClientResponse
  readonly cause: E
}

class NPMErrorImpl extends Data.Error<{
  _tag: string
  cause: any
  request: HttpClientRequest.HttpClientRequest
  response: HttpClientResponse.HttpClientResponse
}> {}

export const NPMError = <Tag extends string, E>(
  tag: Tag,
  cause: E,
  response: HttpClientResponse.HttpClientResponse,
): NPMError<Tag, E> =>
  new NPMErrorImpl({
    _tag: tag,
    cause,
    response,
    request: response.request,
  }) as any
