import { serial } from 'drizzle-orm/pg-core'

import { flow } from 'effect/Function'

import { addRequiredColumn } from '../columnsAdders/index.ts'
import { addUniqueConstraintWithIndex } from '../extraTableConfigsAdders/index.ts'

// TODO: Add also Bigint53 version

export const addAutoGeneratedGloballyUniqueOrderingColumn = flow(
  addRequiredColumn('order', serial),
  addUniqueConstraintWithIndex('order'),
)
