export {
  acquireReleaseConnection,
  closeConnection,
  closeConnectionFromWrapped,
  type DualStateChangesStreamMaker,
  type DualStateChangesStreamMakerFromWrapped,
  type EffectfulMIDIPort,
  getConnectionState,
  getConnectionStateFromWrapped,
  getConnectionStateUnsafe,
  getDeviceState,
  getDeviceStateFromWrapped,
  getDeviceStateUnsafe,
  is,
  makeStateChangesStream,
  makeStateChangesStreamFromWrapped,
  openConnection,
  openConnectionFromWrapped,
  type StateChangeStream,
  type TypeId,
} from './internal/EffectfulMIDIPort.ts'
