export {
  acquireReleaseConnection,
  closeConnection,
  type DualStateChangesStreamMaker,
  type EffectfulMIDIPort,
  type GoodConfig,
  getConnectionState,
  getDeviceState,
  is,
  isConnectionClosed,
  isConnectionOpen,
  isConnectionPending,
  isDeviceConnected,
  isDeviceDisconnected,
  type MatchMutablePropertyConfig,
  makeStateChangesStream,
  matchConnectionState,
  matchDeviceState,
  openConnection,
  type StateChangesStream,
  type StateChangesStreamMakerPortFirst,
  type StateChangesStreamMakerPortLast,
  type TypeId,
} from './internal/EffectfulMIDIPort.ts'
