export {
  acquireReleaseConnection,
  closeConnection,
  closeConnectionFromWrapped,
  type DualStateChangesStreamMaker,
  type DualStateChangesStreamMakerFromWrapped,
  type EffectfulMIDIPort,
  getConnectionState,
  getDeviceState,
  is,
  makeStateChangesStream,
  makeStateChangesStreamFromWrapped,
  openConnection,
  openConnectionFromWrapped,
  type StateChangesStream,
  type StateChangesStreamMakerPortFirst,
  type StateChangesStreamMakerPortLast,
  type TypeId,
} from './internal/EffectfulMIDIPort.ts'
