export {
  acquireReleasePortConnectionByPortId,
  clearPortById,
  closePortConnectionByPortId,
  getInputPortByIdFromContext,
  getOutputPortByIdFromContext,
  getPortByIdFromContext,
  getPortConnectionStateByPortId,
  getPortDeviceStateByPortId,
  makeAllPortsStateChangesStreamFromContext,
  makeInputPortStateChangesStreamByPortId,
  makeMessagesStreamByPortId,
  makeOutputPortStateChangesStreamByPortId,
  makePortStateChangesStreamByPortId,
  matchInputPortConnectionStateByPortId,
  matchInputPortDeviceStateByPortId,
  matchOutputPortConnectionStateByPortId,
  matchOutputPortDeviceStateByPortId,
  matchPortConnectionStateByPortId,
  matchPortDeviceStateByPortId,
  openPortConnectionByPortId,
  sendFromContext,
} from './internal/contextualFunctions.ts'

export {
  AllPortsRecord,
  assert,
  type DualSendMIDIMessageFromAccess,
  EMIDIAccess,
  type EMIDIAccessInstance,
  getAllPortsRecord,
  getInputPortsRecord,
  getOutputPortsRecord,
  InputPortsRecord,
  is,
  layer,
  layerMostRestricted,
  layerSoftwareSynthSupported,
  layerSystemExclusiveAndSoftwareSynthSupported,
  layerSystemExclusiveSupported,
  makeAllPortsStateChangesStream,
  OutputPortsRecord,
  type PolymorphicAccessInstance,
  type RequestMIDIAccessOptions,
  request,
  type SendFromAccessArgs,
  type SendMIDIMessageAccessFirst,
  type SendMIDIMessageAccessLast,
  type SentMessageEffectFromAccess,
  send,
  type TargetPortSelector,
  type TypeId,
} from './internal/EMIDIAccess.ts'
