// remember to make sure there's no ___FromContext and ___ByPortId in
// internal/EMIDIPort.ts and put them into EMIDIAccess

export {
  acquireReleasePortConnectionByPortId as acquireReleaseConnectionById,
  closePortConnectionByPortId as closeConnectionById,
  getPortConnectionStateByPortId as getConnectionStateById,
  getPortDeviceStateByPortId as getDeviceStateById,
  makePortStateChangesStreamByPortId as makeStateChangesStreamById,
  matchPortConnectionStateByPortId as matchConnectionStateById,
  matchPortDeviceStateByPortId as matchDeviceStateById,
  openPortConnectionByPortId as openConnectionById,
} from './internal/contextualFunctions.ts'

export {
  acquireReleaseConnection,
  assert,
  closeConnection,
  type DualMakeStateChangesStream,
  type DualMatchPortState,
  type EMIDIPort,
  getConnectionState,
  getDeviceState,
  is,
  isConnectionClosed,
  isConnectionOpen,
  isConnectionPending,
  isDeviceConnected,
  isDeviceDisconnected,
  type MakeStateChangesStreamPortFirst,
  type MakeStateChangesStreamPortLast,
  type MatcherConfigPlain,
  type MatchResult,
  type MatchStatePortFirst,
  type MatchStatePortLast,
  type MIDIPortMutableProperty,
  makeStateChangesStream,
  matchConnectionState,
  matchDeviceState,
  openConnection,
  type PolymorphicPort,
  type PortStateHandler,
  type StateCaseToHandlerMap,
  type StateChangesStream,
  type TypeId,
} from './internal/EMIDIPort.ts'
