export {
  type DualMakeSpecificMessageStreamFromAccess,
  type DualMakeSpecificMessageStreamFromInput,
  type ForbidNullsStrategy,
  type MakeSpecificMessageStreamAccessFirst,
  type MakeSpecificMessageStreamAccessLast,
  type MakeSpecificMessageStreamAccessLastSecondPart,
  type MakeSpecificMessageStreamInputFirst,
  type MakeSpecificMessageStreamInputLast,
  type MakeSpecificMessageStreamInputLastSecondPart,
  type MakeSpecificMessageStreamResult,
  makeChannelPressureStreamByInput,
  makeChannelPressureStreamByInputIdAndAccess,
  makeChannelPressureStreamByInputIdInContext,
  makeControlChangeStreamByInput,
  makeControlChangeStreamByInputIdAndAccess,
  makeControlChangeStreamByInputIdInContext,
  makeNotePressStreamByInput,
  makeNotePressStreamByInputIdAndAccess,
  makeNotePressStreamByInputIdInContext,
  makeNoteReleaseStreamByInput,
  makeNoteReleaseStreamByInputIdAndAccess,
  makeNoteReleaseStreamByInputIdInContext,
  makePitchBendChangeStreamByInput,
  makePitchBendChangeStreamByInputIdAndAccess,
  makePitchBendChangeStreamByInputIdInContext,
  makeTouchpadPositionUpdateStreamByInput,
  makeTouchpadPositionUpdateStreamByInputIdAndAccess,
  makeTouchpadPositionUpdateStreamByInputIdInContext,
  makeTouchpadReleaseStreamByInput,
  makeTouchpadReleaseStreamByInputIdAndAccess,
  makeTouchpadReleaseStreamByInputIdInContext,
  makeUnknownReplyStreamByInput,
  makeUnknownReplyStreamByInputIdAndAccess,
  makeUnknownReplyStreamByInputIdInContext,
} from './internal/MIDIEventStreams.ts'
