export {
  makeChannelPressureStreamByInputId,
  makeChannelPressureStreamByInputIdAndAccess,
  makeChannelPressureStreamByPort,
  makeControlChangeStreamByInputId,
  makeControlChangeStreamByInputIdAndAccess,
  makeControlChangeStreamByPort,
  makeNotePressStreamByInputId,
  makeNotePressStreamByInputIdAndAccess,
  makeNotePressStreamByPort,
  makeNoteReleaseStreamByInputId,
  makeNoteReleaseStreamByInputIdAndAccess,
  makeNoteReleaseStreamByPort,
  makePitchBendChangeStreamByInputId,
  makePitchBendChangeStreamByInputIdAndAccess,
  makePitchBendChangeStreamByPort,
  makeTouchpadPositionUpdateStreamByInputId,
  makeTouchpadPositionUpdateStreamByInputIdAndAccess,
  makeTouchpadPositionUpdateStreamByPort,
  makeTouchpadReleaseStreamByInputId,
  makeTouchpadReleaseStreamByInputIdAndAccess,
  makeTouchpadReleaseStreamByPort,
  makeUnknownReplyStreamByInputId,
  makeUnknownReplyStreamByInputIdAndAccess,
  makeUnknownReplyStreamByPort,
} from './internal/MIDIEventStreams.ts'
export type { ParsedMIDIMessage } from './internal/Parsing.ts'
