export {
  // fromPolymorphic,
  // polymorphicCheckInDual,
  type FallbackOnUnknownOrAny,
  getStaticMIDIPortInfo,
  type IsEqualFlag,
  isCertainConnectionState,
  isCertainDeviceState,
  isConnectionClosed,
  isConnectionOpen,
  isConnectionPending,
  isDeviceConnected,
  isDeviceDisconnected,
  type MIDIPortStaticFields,
  mapToGlidingStringLogOfLimitedEntriesCount,
  midiPortStaticFields,
  type PolymorphicEffect,
} from './internal/Util.ts'
