export {
  type AudioContextRenderSizeCategory,
  type AudioSinkOptions,
  type AudioSinkType,
  assert,
  currentTime,
  type DecodeAudioData,
  type DecodeAudioDataResult,
  type DecodeAudioDataSourceFirst,
  type DecodeAudioDataSourceLast,
  type DecodeAudioDataSourceLastSecondPart,
  decodeAudioData,
  EAudioContext,
  type EAudioContextInstance as Instance,
  is,
  type MakeAudioContextOptions,
  make,
  type TypeId,
} from './internal/EAudioContext.ts'
