export {
  type AudioContextRenderSizeCategory,
  type AudioSinkOptions,
  type AudioSinkType,
  assert,
  currentTime,
  currentTimeFromContext,
  type DecodeAudioData,
  type DecodeAudioDataSourceFirst,
  type DecodeAudioDataSourceLast,
  type DecodeAudioDataSourceLastSecondPart,
  type DecodedAudioDataEffect,
  decodeAudioData,
  EAudioContext,
  type EAudioContextInstance as Instance,
  is,
  layer,
  type MakeAudioContextOptions,
  make,
  type TypeId,
} from './internal/EAudioContext.ts'
