export {
  assert,
  type CopyFromChannel,
  type CopyFromChannelResult,
  type CopyFromChannelSourceFirst,
  type CopyFromChannelSourceLast,
  type CopyFromChannelSourceLastSecondPart,
  type CopyToChannel,
  type CopyToChannelDestinationFirst,
  type CopyToChannelDestinationLast,
  type CopyToChannelDestinationLastSecondPart,
  type CopyToChannelResult,
  copyFromChannel,
  copyToChannel,
  type EAudioBuffer,
  type GetChannelData,
  type GetChannelDataResult,
  type GetChannelDataSourceFirst,
  type GetChannelDataSourceLast,
  type GetChannelDataSourceLastSecondPart,
  getChannelData,
  is,
  type MakeAudioBufferOptions,
  make,
  type TypeId,
} from './internal/EAudioBuffer.ts'
