export {
  type AudioContextRenderSizeCategory,
  type AudioSinkOptions,
  type AudioSinkType,
  assert,
  type CurrentTime,
  type CurrentTimeEffect,
  currentTime,
  currentTimeFromContext,
  type DecodeAudioData,
  type DecodeAudioDataError,
  type DecodeAudioDataFromContext,
  type DecodeAudioDataSourceFirst,
  type DecodeAudioDataSourceLast,
  type DecodeAudioDataSourceLastSecondPart,
  type DecodeAudioDataWith,
  type DecodedAudioDataEffect,
  type DecodedAudioDataEffectWith,
  decodeAudioData,
  decodeAudioDataFromContext,
  EAudioContext,
  type EAudioContextInstance as Instance,
  is,
  layer,
  type MakeAudioContextOptions,
  type MakeError,
  make,
  type TypeId,
  unsafeNativeAudioContext,
} from './internal/EAudioContext.ts'
