import {
  addAutoGeneratedGloballyUniqueOrderingColumn,
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk,
  addBigint53RequiredColumnWithFk,
  addColumn,
  addColumns,
  addCompositePrimaryKey,
  addCreatedAndUpdatedDateColumns,
  addCreatedAtDateColumn,
  addIntegerIdColumnAsPrimaryKey,
  addIntegerRequiredColumnWithFk,
  addOptionalDescription,
  addPrimaryKey,
  addRequiredColumn,
  addRequiredColumns,
  addRequiredNameWithOptionalDescription,
  addUniqueConstraintWithIndex,
  finalizePgTable,
  initPgTable,
} from 'drizzle-fp'
import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  real,
  smallint,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core'

import { pipe } from 'effect/Function'

export const abstractQuestionAnswerChoiceTypeEnum = pgEnum(
  'abstract_question_answer_choice_type_enum',
  ['selectOne', 'selectMany', 'noSelect'],
)
export const abstractQuestionDataTypeOfAnswersEnum = pgEnum(
  'abstract_question_data_type_of_answers_enum',
  ['string', 'integer', 'decimal', 'date'],
)
export const educationalSpaceAccessScopeTypeEnum = pgEnum(
  'educational_space_access_scope_type_enum',
  // TODO: add hierarchial meta-info about permissions
  [
    'addOwnAbstractTestsIntoEducationalSpaceCatalog',
    'viewLaunchedTests',
    'modifyLaunchedTests',
    'viewUserGroups',
    'modifyUserGroups',
    'modifySpaceInfo',
    'modifyAccessScopesInSpace',
    'deleteOwnSpace',
  ],
)
export const launchedTestAccessScopeTypeEnum = pgEnum(
  'launched_test_access_scope_type_enum',
  ['viewAnalytics', 'viewUsersFinishedTest', 'makeTestAttempts'],
)
export const launchedTestVariantAccessScopeTypeEnum = pgEnum(
  'launched_test_variant_access_scope_type_enum',
  ['viewAnalytics', 'viewUsersFinishedTest', 'makeTestAttempts'],
)
export const testAnalyticsModuleSupportEnum = pgEnum(
  'test_analytics_module_support_enum',
  ['analyticsOfUserAttempt', 'analyticsOfAllAttemptsOfLaunchedTest'],
)
export const testAttemptStatusEnum = pgEnum('test_attempt_status_enum', [
  'draft',
  'finishedAttempt',
])
export const userGroupManagementAccessScopeTypeEnum = pgEnum(
  'user_group_management_access_scope_type_enum',
  [
    'inviteUsers',
    'removeUsers',
    'viewUsers',
    'launchTest',
    'assignAliasesOfUsersFromSubordinateGroups',
  ],
)

// TODO: migrate all columns when PG 18 will come out (september-october 2025)
// 1. createdAt
// to
// 1. external_${tableName}_uuid (v7)
// 2. virtual generated always createdAt as (get_timestamp_tz_from_uuidv7(external_${tableName}_uuid))
// (_id columns still present)

// TODO: soft deletion on everything (+ consistency somehow?)

const addUserGroupIdColumnAndFk = addIntegerRequiredColumnWithFk(
  'userGroupId',
  () => userGroup.id,
)
const addCreatedByUserIdColumnAndFk = addIntegerRequiredColumnWithFk(
  'createdByUserId',
  () => user.fastId,
)
const addAbstractTestIdColumnAndFk = addBigint53RequiredColumnWithFk(
  'abstractTestId',
  () => abstractTest.id,
)
const addEducationalSpaceIdColumnAndFk = addIntegerRequiredColumnWithFk(
  'educationalSpaceId',
  () => educationalSpace.id,
)
const addUserIdColumnAndFk = addIntegerRequiredColumnWithFk(
  'userId',
  () => user.fastId,
)
const addLaunchedByUserIdColumnAndFk = addIntegerRequiredColumnWithFk(
  'launchedByUserId',
  () => user.fastId,
)

const addColumnsWithCompositeFkToAbstractAnswerOption =
  addBigint53RequiredColumnsWithCompositeFk(() => abstractAnswerOption, {
    abstractQuestionId: 'abstractQuestionId',
    abstractAnswerOptionId: 'id',
  })

export const { user } = pipe(
  initPgTable('user'),
  addColumn('fastId', () => integer(`user_id`).generatedAlwaysAsIdentity()),
  addRequiredColumn('id', () => text(`user_uuid_for_better_auth`)), // only for fucked up better auth
  addPrimaryKey('fastId'),
  addRequiredColumns(() => ({
    howToAddressMe: varchar(),
    email: varchar(),
    isEmailVerified: boolean(), // for better auth
    canCreateEducationalSpaces: boolean(),
    // salt: varchar(),
    // passwordHash: varchar(),
  })),
  addColumn('avatar', text),
  addUniqueConstraintWithIndex('email'),
  addUniqueConstraintWithIndex('id'),
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

// https://github.com/NotLuksus/sphericon-chat/blob/main/packages/auth/src/service.ts
// https://github.com/sundaray/next-effect/blob/bdf72719c9ab2fcaf69d4e48da7e13e35b73e06c/db/schema.ts
// export const usersTable = pgTable('users', t => ({
//   id: t.text().primaryKey(),
//   name: t.text().notNull(),
//   email: t.text().notNull().unique(),
//
//   image: t.text(),
//   createdAt: t.timestamp().notNull(),
//   updatedAt: t.timestamp().notNull(),
// }));
export const account = pgTable('account', t => ({
  id: t.text().primaryKey(),
  accountId: t.text().notNull(),
  providerId: t.text().notNull(),
  userId: t
    .text()
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  // accessToken: t.text(),
  // refreshToken: t.text(),
  // idToken: t.text(),
  // accessTokenExpiresAt: t.timestamp(),
  // refreshTokenExpiresAt: t.timestamp(),
  // scope: t.text(),
  password: t.text(),
  createdAt: t.timestamp().notNull(),
  updatedAt: t.timestamp().notNull(),
}))

export const session = pgTable('session', t => ({
  id: t.text().primaryKey(),
  expiresAt: t.timestamp().notNull(),
  token: t.text().notNull().unique(),
  createdAt: t.timestamp().notNull(),
  updatedAt: t.timestamp().notNull(),
  ipAddress: t.text(),
  userAgent: t.text(),
  userId: t
    .text()
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
}))
// export const verificationsTable = pgTable('verifications', t => ({
//   id: t.text().primaryKey(),
//   identifier: t.text().notNull(),
//   value: t.text().notNull(),
//   expiresAt: t.timestamp().notNull(),
//   createdAt: t.timestamp(),
//   updatedAt: t.timestamp(),
// }));
// export const jwksTable = pgTable('jwks', t => ({
//   id: t.text().primaryKey(),
//   publicKey: t.text().notNull(),
//   privateKey: t.text().notNull(),
//   createdAt: t.timestamp().notNull(),
// }));

// export const { userIdentity } = pipe(
//   initPgTable('user_identity'),
//   addBigint53IdColumnAsPrimaryKey,
//   finalizePgTable,
// );

export const { abstractTest } = pipe(
  initPgTable('abstract_test'),
  addBigint53IdColumnAsPrimaryKey,
  addRequiredNameWithOptionalDescription,
  addRequiredColumns(() => ({
    goal: varchar(),
    // TODO: Trigger on `update set isReadyToLaunch = true` or `delete from
    // "correctOptionsTable"` to ensure presence of (depending on the
    // question/test mode `at least one` or `at least two`) correct options for tests that are marked
    // as ready to launch
    isReadyToLaunch: boolean().default(false),
    isPublicWorldwide: boolean().default(false),
  })),
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

export const { abstractTestVariant } = pipe(
  initPgTable('abstract_test_variant'),
  addBigint53IdColumnAsPrimaryKey,
  addOptionalDescription,
  addRequiredColumns(() => ({
    isArtificiallyGenerated: boolean(),
    isReadyToLaunch: boolean().default(false),
    isPublicWorldwide: boolean().default(false),
  })),
  addAbstractTestIdColumnAndFk,
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  addUniqueConstraintWithIndex('abstractTestId', 'id'),
  finalizePgTable,
)

export const { abstractTestStage } = pipe(
  initPgTable('abstract_test_stage'),
  addBigint53IdColumnAsPrimaryKey,
  addAutoGeneratedGloballyUniqueOrderingColumn,
  addRequiredNameWithOptionalDescription,
  addBigint53RequiredColumnWithFk(
    'abstractTestVariantId',
    () => abstractTestVariant.id,
  ),
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  addUniqueConstraintWithIndex('abstractTestVariantId', 'id'),
  finalizePgTable,
)

export const { abstractQuestion } = pipe(
  initPgTable('abstract_question'),
  addBigint53IdColumnAsPrimaryKey,
  addRequiredNameWithOptionalDescription,
  addBigint53RequiredColumnWithFk(
    'abstractTestStageId',
    () => abstractTestStage.id,
  ),
  addAutoGeneratedGloballyUniqueOrderingColumn,
  addColumns(() => ({
    // isRequired: boolean().default(true),
    isAdditionalFreeFieldAnswerEnabled: boolean().default(false).notNull(),
    answerChoiceType: abstractQuestionAnswerChoiceTypeEnum()
      .default('selectOne')
      .notNull(),
    // TODO: CHECK to validate presence or absence of dataTypeOfFreeFieldAnswers depending on isAdditionalFreeFieldAnswerEnabled
    dataTypeOfFreeFieldAnswers: abstractQuestionDataTypeOfAnswersEnum(),
  })),
  addUniqueConstraintWithIndex('abstractTestStageId', 'id'),
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

// export const { abstractChoiceQuestion } = pipe(
//   initPgTable('abstract_choice_question'),
//   addBigint53RequiredColumnWithFk(
//     'abstractQuestionId',
//     () => abstractQuestion.id,
//   ),
//   finalizePgTable,
// );

// export const { abstractFreeAnswerQuestion } = pipe(
//   initPgTable('abstract_free_answer_question'),
//   addBigint53RequiredColumnWithFk(
//     'abstractQuestionId',
//     () => abstractQuestion.id,
//   ),
//   finalizePgTable,
// );

// export const { abstractSingleRightChoiceQuestion } = pipe(
//   initPgTable('abstract_single_right_choice_question'),
//   addBigint53RequiredColumnWithFk(
//     'abstractQuestionId',
//     () => abstractQuestion.id,
//   ),
//   finalizePgTable,
// );

// export const { abstractMultipleRightChoiceQuestion } = pipe(
//   initPgTable('abstract_multiple_right_choice_question'),
//   finalizePgTable,
// );

export const { abstractAnswerOption } = pipe(
  initPgTable('abstract_answer_option'),
  addBigint53IdColumnAsPrimaryKey,
  addAutoGeneratedGloballyUniqueOrderingColumn,
  addOptionalDescription,
  // TODO: constraint valid when (isAdditionalFreeFieldAnswerEnabled ? textOfSelectableAnswer === null : textOfSelectableAnswer !== null && textOfSelectableAnswer !== '')
  // TODO: trigger to validate this to follow abstractQuestion.answerChoiceType
  addColumn('textOfSelectableAnswer', varchar),
  addBigint53RequiredColumnWithFk(
    'abstractQuestionId',
    () => abstractQuestion.id,
  ),
  addUniqueConstraintWithIndex('abstractQuestionId', 'id'),
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

export const { singleCorrectAbstractAnswerOption } = pipe(
  initPgTable('single_correct_abstract_answer_option'),
  addColumnsWithCompositeFkToAbstractAnswerOption,
  addPrimaryKey('abstractQuestionId'),
  addRequiredColumn('scoreContribution', real),
  finalizePgTable,
)

export const { availableForLaunchTest } = pipe(
  initPgTable('available_for_launch_test'),
  addAbstractTestIdColumnAndFk,
  addEducationalSpaceIdColumnAndFk,
  addCreatedAtDateColumn,
  addCompositePrimaryKey('abstractTestId', 'educationalSpaceId'),
  finalizePgTable,
)

const addReorderingFlagsColumns = addColumns(() => ({
  shouldReorderStagesForEachStudent: boolean(),
  shouldReorderQuestionsInStagesForEachStudent: boolean(),
  shouldReorderAnswersInStagesForEachStudent: boolean(),
}))

export const { launchedTest } = pipe(
  initPgTable('launched_test'),
  addBigint53IdColumnAsPrimaryKey,
  addColumns(() => ({
    openingDate: timestamp({ withTimezone: true, mode: 'string' }),
    closingDate: timestamp({ withTimezone: true, mode: 'string' }),
    maximumAttemptDurationInMinutes: smallint(),
    maximumAmountOfAttempts: smallint(),
  })),
  addReorderingFlagsColumns,
  addAbstractTestIdColumnAndFk,
  addEducationalSpaceIdColumnAndFk,
  addLaunchedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  addUniqueConstraintWithIndex('abstractTestId', 'id'),
  finalizePgTable,
)

export const { launchedTestVariant } = pipe(
  initPgTable('launched_test_variant'),
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk(() => abstractTestVariant, {
    abstractTestId: 'abstractTestId',
    abstractTestVariantId: 'id',
  }),
  addBigint53RequiredColumnsWithCompositeFk(() => launchedTest, {
    abstractTestId: 'abstractTestId',
    launchedTestId: 'id',
  }),
  addReorderingFlagsColumns,
  addCreatedAndUpdatedDateColumns,
  addUniqueConstraintWithIndex('abstractTestVariantId', 'id'),
  addUniqueConstraintWithIndex('launchedTestId', 'abstractTestVariantId'),
  finalizePgTable,
)

// TODO: add trigger to validate maximumAmountOfAttempts
export const { testVariantAttempt } = pipe(
  initPgTable('test_variant_attempt'),
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk(() => launchedTestVariant, {
    abstractTestVariantId: 'abstractTestVariantId',
    launchedTestVariantId: 'id',
  }),
  addColumns(() => ({
    finishedAtDate: timestamp({ withTimezone: true, mode: 'string' }),
    lastSavedAtDate: timestamp({ withTimezone: true, mode: 'string' }),
    status: testAttemptStatusEnum().notNull(),
  })),
  addUserIdColumnAndFk,
  addUniqueConstraintWithIndex('abstractTestVariantId', 'id'),
  addCreatedAtDateColumn,
  finalizePgTable,
)

export const { testStageInstance } = pipe(
  initPgTable('test_stage_instance'),
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk(() => testVariantAttempt, {
    abstractTestVariantId: 'abstractTestVariantId',
    testVariantAttemptId: 'id',
  }),
  addBigint53RequiredColumnsWithCompositeFk(() => abstractTestStage, {
    abstractTestVariantId: 'abstractTestVariantId',
    abstractTestStageId: 'id',
  }),
  addAutoGeneratedGloballyUniqueOrderingColumn,
  addUniqueConstraintWithIndex('abstractTestStageId', 'id'),
  addUniqueConstraintWithIndex('testVariantAttemptId', 'abstractTestStageId'),
  finalizePgTable,
)

export const { questionInstance } = pipe(
  initPgTable('question_instance'),
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk(() => testStageInstance, {
    abstractTestStageId: 'abstractTestStageId',
    testStageInstanceId: 'id',
  }),
  addBigint53RequiredColumnsWithCompositeFk(() => abstractQuestion, {
    abstractTestStageId: 'abstractTestStageId',
    abstractQuestionId: 'id',
  }),
  addAutoGeneratedGloballyUniqueOrderingColumn,
  // TODO: trigger to validate presence or absence of freeFieldAnswer depending on abstractQuestion.isAdditionalFreeFieldAnswerEnabled
  addColumn('freeFieldAnswer', varchar),
  addUniqueConstraintWithIndex('abstractQuestionId', 'id'),
  addUniqueConstraintWithIndex('testStageInstanceId', 'abstractQuestionId'),
  finalizePgTable,
)

export const { answerOptionInstance } = pipe(
  initPgTable('answer_option_instance'),
  // TODO: Add finalized, fixated score column
  addBigint53IdColumnAsPrimaryKey,
  addBigint53RequiredColumnsWithCompositeFk(() => questionInstance, {
    abstractQuestionId: 'abstractQuestionId',
    questionInstanceId: 'id',
  }),
  addColumnsWithCompositeFkToAbstractAnswerOption,
  addAutoGeneratedGloballyUniqueOrderingColumn,
  // TODO: trigger (and maybe exclusion constraint or just index?) to validate isSelected
  addColumn('isSelected', () => boolean().default(false)),
  addUniqueConstraintWithIndex('abstractAnswerOptionId', 'id'),
  addUniqueConstraintWithIndex('questionInstanceId', 'abstractAnswerOptionId'),
  finalizePgTable,
)

export const { educationalSpace } = pipe(
  initPgTable('educational_space'),
  addIntegerIdColumnAsPrimaryKey,
  addRequiredNameWithOptionalDescription,
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

export const { userGroup } = pipe(
  initPgTable('user_group'),
  addIntegerIdColumnAsPrimaryKey,
  addRequiredNameWithOptionalDescription,
  addEducationalSpaceIdColumnAndFk,
  addCreatedByUserIdColumnAndFk,
  addCreatedAndUpdatedDateColumns,
  finalizePgTable,
)

export const { educationalSpaceAccessScope } = pipe(
  initPgTable('educational_space_access_scope'),
  addRequiredColumn('type', educationalSpaceAccessScopeTypeEnum),
  addUserGroupIdColumnAndFk,
  addCreatedAtDateColumn,
  addCompositePrimaryKey('userGroupId', 'type'),
  finalizePgTable,
)

export const { launchedTestAccessScope } = pipe(
  initPgTable('launched_test_access_scope'),
  addRequiredColumn('type', launchedTestAccessScopeTypeEnum),
  addUserGroupIdColumnAndFk,
  addBigint53RequiredColumnWithFk('launchedTestId', () => launchedTest.id),
  addCreatedAtDateColumn,
  addCompositePrimaryKey('userGroupId', 'launchedTestId', 'type'),
  finalizePgTable,
)

export const { launchedTestVariantAccessScope } = pipe(
  initPgTable('launched_test_variant_access_scope'),
  addRequiredColumn('type', launchedTestVariantAccessScopeTypeEnum),
  addUserGroupIdColumnAndFk,
  addBigint53RequiredColumnWithFk(
    'launchedTestVariantId',
    () => launchedTestVariant.id,
  ),
  addCreatedAtDateColumn,
  addCompositePrimaryKey('userGroupId', 'launchedTestVariantId', 'type'),
  finalizePgTable,
)

export const { userGroupManagementAccessScope } = pipe(
  initPgTable('user_group_management_access_scope'),
  addRequiredColumn('type', userGroupManagementAccessScopeTypeEnum),
  addIntegerRequiredColumnWithFk('leaderUserGroupId', () => userGroup.id),
  addIntegerRequiredColumnWithFk('subordinateUserGroupId', () => userGroup.id),
  addCreatedAtDateColumn,
  // TODO: make both userGroupIds be of the 1 educational space
  addCompositePrimaryKey('leaderUserGroupId', 'subordinateUserGroupId', 'type'),
  finalizePgTable,
)

export const { userToUserGroup } = pipe(
  initPgTable('user_to_user_group'),
  addUserGroupIdColumnAndFk,
  addUserIdColumnAndFk,
  addCreatedAtDateColumn,
  addCompositePrimaryKey('userGroupId', 'userId'),
  finalizePgTable,
)

// Tags need ownership of anything, or else if we allow anybody to contribute
// tags without responsibility, we get garbage, but without allowing users
// create their own tags, there's no point in them

// export const { tag } = pipe(
//   initPgTable('tag'),
//   addIntegerIdColumnAsPrimaryKey,
//   addRequiredNameWithOptionalDescription,
//   addCreatedAndUpdatedDateColumns,
//   // TODO: Make tree topic structure?
//   addUniqueConstraintWithIndex('name'),
//   finalizePgTable
// );

// export const { testAnalyticsModule } = pipe(
//   initPgTable('test_analytics_module'),
//   addIntegerIdColumnAsPrimaryKey,
//   addRequiredNameWithOptionalDescription,
//   addRequiredColumns(() => ({
//     testAnalyticsModuleUuid: uuid(),
//     support: testAnalyticsModuleSupportEnum(),
//   })),
//   addUniqueConstraintWithIndex('testAnalyticsModuleUuid'),
//   addCreatedAtDateColumn,
//   finalizePgTable
// );

// export const { answerOptionIntoTagContribution } = pipe(
//   initPgTable('answer_option_into_tag_contribution'),
//   addRequiredColumns(() => ({ weight: real() })),
//   addIntegerRequiredColumnWithFk(
//     'abstractAnswerOptionId',
//     () => abstractAnswerOption.id
//   ),
//   addIntegerRequiredColumnWithFk('tagId', () => tag.id),
//   addCreatedAndUpdatedDateColumns,
//   addCompositePrimaryKey('abstractAnswerOptionId', 'tagId'),
//   finalizePgTable
// );

// export const { testAnalyticsModuleToAbstractTest } = pipe(
//   initPgTable('test_analytics_module_to_abstract_test'),
//   addIntegerRequiredColumnWithFk(
//     'testAnalyticsModuleId',
//     () => testAnalyticsModule.id
//   ),
//   addAbstractTestIdColumnAndFk,
//   addCreatedAtDateColumn,
//   addCompositePrimaryKey('testAnalyticsModuleId', 'abstractTestId'),
//   finalizePgTable
// );
